import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "pt" | "es" | "en" | "id";

export const translations = {
  pt: {
    // Navigation / Header / Footer
    library: "Biblioteca",
    admin: "Admin",
    toggleTheme: "Alternar modo claro e escuro",
    login: "Entrar",
    register: "Cadastrar",
    logout: "Sair da Conta",
    profile: "Meu Perfil",
    version: "Versão",
    online: "Online",
    bthDigital: "BTH Digital",
    bthLibrary: "Biblioteca BTH",
    language: "Idioma",
    
    // Home Page
    archive: "Acervo",
    welcomeUser: "Bem-vindo(a), {name}. Explore o acervo digital.",
    exploreArchive: "Explore histórias incríveis e salve sua leitura.",
    exploreStories: "Explore histórias incríveis e salve sua leitura.",
    history: "Histórico",
    favorites: "Favoritos",
    searchPlaceholder: "Buscar título, autor ou gênero...",
    mostRecent: "Mais Recentes",
    mostPopular: "Mais Populares",
    noStoriesFound: "Nenhuma história encontrada.",
    noFavoritesFound: "Você ainda não adicionou histórias aos favoritos.",
    noHistoryFound: "Seu histórico de leitura está vazio.",
    continueReading: "Continuar",
    by: "Por",
    publishedOn: "Publicado em",
    pageOf: "Pág. {page} de {total}",
    readTime: "min de leitura",
    
    // Reader Page
    backToLibrary: "Voltar à Biblioteca",
    readingResumed: "Leitura Retomada",
    readingRestored: "Sua leitura foi restaurada automaticamente na página {page}.",
    restartPage1: "Reiniciar (Pág. 1)",
    goTo: "Ir para:",
    loadingPage: "Carregando página...",
    previous: "Anterior",
    next: "Próxima",
    approvedComments: "Comentários Aprovados",
    endOfStory: "Fim da História",
    enjoyedReading: "Gostou da leitura? Deixe sua avaliação.",
    reviewSent: "Avaliação Enviada!",
    reviewSavedPending: "Sua avaliação foi registrada. Caso tenha incluído um comentário, ele passará pela moderação antes de ser publicado.",
    yourRating: "Sua Nota",
    commentLabel: "Comentário (Sujeito à moderação)",
    commentPlaceholder: "Escreva sua opinião sobre a história...",
    moderationNotice: "Os comentários são revisados pelo administrador antes de ficarem visíveis publicamente.",
    sending: "Enviando...",
    submitReview: "Enviar Avaliação",
    loadingStory: "Abrindo história...",
    storyNotFound: "História não encontrada.",
    reader: "Leitor",
    errorSubmitReview: "Erro ao enviar avaliação.",
    pageNotFound: "Página não encontrada.",
    errorLoadingPage: "Erro ao carregar página.",
    
    // Auth Modal
    changePassword: "Alterar Senha",
    myProfile: "Meu Perfil",
    currentPassword: "Senha Atual",
    newPassword: "Nova Senha",
    newPasswordPlaceholder: "Mínimo de 6 caracteres",
    currentPasswordPlaceholder: "Sua senha atual",
    saveNewPassword: "Salvar Nova Senha",
    updating: "Atualizando...",
    enterLibrary: "Entrar na Biblioteca",
    createAccount: "Criar uma Conta",
    recoverPassword: "Recuperar Senha",
    accessFavorites: "Acesse seus favoritos e acompanhe seu progresso de leitura.",
    signupToSave: "Cadastre-se para salvar suas histórias e avaliações.",
    forgotPasswordInstructions: "Informe seu e-mail para definir uma nova senha.",
    email: "E-mail",
    password: "Senha",
    confirmPassword: "Confirmar Senha",
    confirmPasswordPlaceholder: "Digite a senha novamente",
    nameLabel: "Nome Completo",
    namePlaceholder: "Seu nome",
    forgotPasswordLink: "Esqueci minha senha",
    alreadyHaveAccount: "Já tem uma conta?",
    dontHaveAccount: "Ainda não possui uma conta?",
    forgotPasswordStep1Instructions: "Informe o e-mail da sua conta para redefinir a senha diretamente na plataforma.",
    passwordStrengthTip: "Dica: Utilize letras, números e no mínimo 6 caracteres para uma senha forte.",
    passwordMismatch: "As senhas informadas não coincidem.",
    passwordMinLength: "A senha deve ter no mínimo 6 caracteres.",
    fillAllFields: "Preencha a senha atual e a nova senha.",
    passwordChangedSuccess: "Sua senha foi alterada com sucesso!",
    successLabel: "Sucesso",
    errorLabel: "Erro",
    forgotStep3Success: "Sua senha foi redefinida com sucesso diretamente no site. Você já pode entrar com suas novas credenciais.",
    forgotStep3Title: "Senha Redefinida!",
    forgotStep3Button: "Ir para o Login",
    entering: "Entrando...",
    creatingAccount: "Criando Conta...",
    checking: "Verificando...",
    saving: "Salvando...",
    passwordGuideline: "Sua senha deve conter pelo menos 6 caracteres.",
    passwordGuidelineStrength: "Crie uma senha segura contendo no mínimo 6 caracteres, combinando letras e números.",
    passwordGuidelineStrengthTitle: "Orientação para Senha Forte",
    forgotStep1InstructionsEmail: "Informe o e-mail da sua conta para redefinir a senha diretamente na plataforma.",
    
    // Admin Page
    adminPanel: "Painel Admin",
    publish: "Publicar",
    manage: "Gerenciar",
    moderateComments: "Moderar Comentários",
    storyTitle: "Título da História",
    storyTitlePlaceholder: "Ex: O Segredo das Estrelas",
    authorPlaceholder: "Ex: Machado de Assis",
    publishDate: "Data de Publicação",
    coverImageLabel: "Imagem de Capa (JPEG/PNG)",
    coverImagePlaceholder: "Clique para selecionar a capa",
    storyFileLabel: "Arquivo da História (DOCX)",
    storyFilePlaceholder: "Clique para selecionar o DOCX",
    authorizeDrive: "Autorizar Google Drive para Upload",
    publishStory: "Publicar História",
    publishing: "Publicando...",
    loadingStories: "Carregando histórias do banco de dados...",
    noStoriesAdmin: "Nenhuma história encontrada no banco de dados.",
    editStory: "Editar História",
    saveChanges: "Salvar Alterações",
    cancel: "Cancelar",
    deleteLabel: "Apagar",
    editLabel: "Editar",
    commentsPending: "Pendentes",
    commentsApproved: "Aprovados",
    commentsRejected: "Rejeitados/Ocultos",
    all: "Todos",
    updateList: "Atualizar Lista",
    editTitle: "Título",
    editAuthor: "Autor",
    editTags: "Tags (separadas por vírgula)",
    editTagsPlaceholder: "Romance, Fantasia, Drama",
    refresh: "Atualizar",
    loginWithGoogle: "Entrar com Google",
    adminAccess: "Acesso Admin",
    restrictedAccess: "Acesso Restrito",
    restrictedAccessDesc: "Esta área é exclusiva para administradores da biblioteca.",
    goToLibrary: "Ir para a Biblioteca",
    exitAccount: "Sair da Conta",
    emptyFieldsError: "O título e o autor não podem ficar vazios.",
    storyUpdatedSuccess: "História atualizada com sucesso!",
    storyDeletedSuccess: 'A história "{title}" foi apagada do banco de dados.',
    commentsApprovalTitle: "Moderação de Comentários",
    approve: "Aprovar",
    reject: "Rejeitar",
    hide: "Ocultar",
    noCommentsFound: "Nenhum comentário encontrado.",
    statusLabel: "Status",
    userLabel: "Usuário",
    textLabel: "Comentário",
    ratingLabel: "Avaliação",
    actionsLabel: "Ações",
    any: "Qualquer",
    startingFiles: "Iniciando arquivos...",
    initialPrep: "Preparação inicial",
    coverProcessing: "Processamento da imagem de capa",
    docxProcessing: "Processamento do documento Word (.docx)",
    docxInvalid: "O documento Word lido não possui páginas válidas.",
    tagGeneration: "Geração automática de gêneros e tags",
    dbCreation: "Criação do registro principal no banco de dados",
    dbPageSending: "Envio das páginas no banco de dados ({end} de {total})",
    publishSuccess: "Publicação concluída com sucesso!",
    stageFailed: "Falha na etapa: {stage}",
    realTimeError: "Erro em Tempo Real ({stage})",
    errorProcess: "Erro durante o processo: ",
    errorUpdatingStory: "Erro ao atualizar história: ",
    errorDeletingStory: "Erro ao apagar história: ",
    errorUpdatingCommentStatus: "Erro ao atualizar status do comentário.",
    loginFailed: "Login falhou",
    unknownAuthor: "Autor desconhecido",
    recentDate: "Data recente",
    approved: "Aprovado",
    pending: "Pendente",
    rejected: "Rejeitado",
    pages: "páginas",
    publishedAt: "Publicado em: {date}",
    confirmDeleteTitle: "Confirmar Exclusão",
    irreversibleAction: "Esta ação é irreversível",
    confirmDeletePrompt: "Tem certeza de que deseja apagar a história {title} permanentemente do banco de dados?",
    confirmDeleteWarning: "Esta ação removerá a história, todas as suas páginas e todas as avaliações do banco de dados.",
    yesDelete: "Sim, Apagar",
    noCommentsCategory: "Nenhum comentário nesta categoria.",
    loadingComments: "Carregando comentários para moderação..."
  },
  es: {
    // Navigation / Header / Footer
    library: "Biblioteca",
    admin: "Admin",
    toggleTheme: "Alternar modo claro y oscuro",
    login: "Iniciar Sesión",
    register: "Registrarse",
    logout: "Cerrar Sesión",
    profile: "Mi Perfil",
    version: "Versión",
    online: "En línea",
    bthDigital: "BTH Digital",
    bthLibrary: "Biblioteca BTH",
    language: "Idioma",
    
    // Home Page
    archive: "Colección",
    welcomeUser: "Bienvenido(a), {name}. Explora la colección digital.",
    exploreArchive: "Explora historias increíbles y guarda tu lectura.",
    exploreStories: "Explora historias increíbles y guarda tu lectura.",
    history: "Historial",
    favorites: "Favoritos",
    searchPlaceholder: "Buscar título, autor o género...",
    mostRecent: "Más Recientes",
    mostPopular: "Más Populares",
    noStoriesFound: "No se encontraron historias.",
    noFavoritesFound: "Aún no has añadido historias a tus favoritos.",
    noHistoryFound: "Tu historial de lectura está vacío.",
    continueReading: "Continuar",
    by: "Por",
    publishedOn: "Publicado el",
    pageOf: "Pág. {page} de {total}",
    readTime: "min de lectura",
    
    // Reader Page
    backToLibrary: "Volver a la Biblioteca",
    readingResumed: "Lectura Reanudada",
    readingRestored: "Tu lectura se restauró automáticamente en la página {page}.",
    restartPage1: "Reiniciar (Pág. 1)",
    goTo: "Ir a:",
    loadingPage: "Cargando página...",
    previous: "Anterior",
    next: "Siguiente",
    approvedComments: "Comentarios Aprobados",
    endOfStory: "Fin de la Historia",
    enjoyedReading: "¿Te gustó la lectura? Deja tu reseña.",
    reviewSent: "¡Reseña Enviada!",
    reviewSavedPending: "Tu reseña ha sido registrada. Si incluiste un comentario, pasará por moderación antes de ser publicado.",
    yourRating: "Tu Calificación",
    commentLabel: "Comentario (Sujeto a moderación)",
    commentPlaceholder: "Escribe tu opinión sobre la historia...",
    moderationNotice: "Los comentarios son revisados por el administrador antes de ser visibles públicamente.",
    sending: "Enviando...",
    submitReview: "Enviar Reseña",
    loadingStory: "Abriendo historia...",
    storyNotFound: "Historia no encontrada.",
    reader: "Lector",
    errorSubmitReview: "Error al enviar la reseña.",
    pageNotFound: "Página no encontrada.",
    errorLoadingPage: "Error al cargar la página.",
    
    // Auth Modal
    changePassword: "Cambiar Contraseña",
    myProfile: "Mi Perfil",
    currentPassword: "Contraseña Actual",
    newPassword: "Nueva Contraseña",
    newPasswordPlaceholder: "Mínimo de 6 caracteres",
    currentPasswordPlaceholder: "Tu contraseña actual",
    saveNewPassword: "Guardar Nueva Contraseña",
    updating: "Actualizando...",
    enterLibrary: "Ingresar a la Biblioteca",
    createAccount: "Crear una Cuenta",
    recoverPassword: "Recuperar Contraseña",
    accessFavorites: "Accede a tus favoritos y sigue tu progreso de lectura.",
    signupToSave: "Regístrate para guardar tus historias y reseñas.",
    forgotPasswordInstructions: "Ingresa tu correo para definir una nueva contraseña.",
    email: "Correo electrónico",
    password: "Contraseña",
    confirmPassword: "Confirmar Contraseña",
    confirmPasswordPlaceholder: "Ingresa la contraseña de nuevo",
    nameLabel: "Nombre Completo",
    namePlaceholder: "Tu nombre",
    forgotPasswordLink: "Olvidé mi contraseña",
    alreadyHaveAccount: "¿Ya tienes una cuenta?",
    dontHaveAccount: "¿Aún no tienes una cuenta?",
    forgotPasswordStep1Instructions: "Ingresa el correo de tu cuenta para restablecer la contraseña directamente en la plataforma.",
    passwordStrengthTip: "Consejo: Usa letras, números y al menos 6 caracteres para una contraseña fuerte.",
    passwordMismatch: "Las contraseñas ingresadas no coinciden.",
    passwordMinLength: "La contraseña debe tener al menos 6 caracteres.",
    fillAllFields: "Completa la contraseña actual y la nueva contraseña.",
    passwordChangedSuccess: "¡Tu contraseña ha sido cambiada con éxito!",
    successLabel: "Éxito",
    errorLabel: "Error",
    forgotStep3Success: "Tu contraseña ha sido restablecida con éxito en el sitio. Ya puedes iniciar sesión con tus nuevas credenciales.",
    forgotStep3Title: "¡Contraseña Restablecida!",
    forgotStep3Button: "Ir al Inicio de Sesión",
    entering: "Iniciando sesión...",
    creatingAccount: "Creando Cuenta...",
    checking: "Verificando...",
    saving: "Guardando...",
    passwordGuideline: "Tu contraseña debe contener al menos 6 caracteres.",
    passwordGuidelineStrength: "Crea una contraseña segura que contenga al menos 6 caracteres, combinando letras y números.",
    passwordGuidelineStrengthTitle: "Guía de Contraseña Fuerte",
    forgotStep1InstructionsEmail: "Ingresa el correo de tu cuenta para restablecer tu contraseña directamente en la plataforma.",
    
    // Admin Page
    adminPanel: "Panel de Admin",
    publish: "Publicar",
    manage: "Gestionar",
    moderateComments: "Moderar Comentarios",
    storyTitle: "Título de la Historia",
    storyTitlePlaceholder: "Ej: El Secreto de las Estrellas",
    authorPlaceholder: "Ej: Miguel de Cervantes",
    publishDate: "Fecha de Publicación",
    coverImageLabel: "Imagen de Portada (JPEG/PNG)",
    coverImagePlaceholder: "Haz clic para seleccionar la portada",
    storyFileLabel: "Archivo de la Historia (DOCX)",
    storyFilePlaceholder: "Haz clic para seleccionar el DOCX",
    authorizeDrive: "Autorizar Google Drive para Subir",
    publishStory: "Publicar Historia",
    publishing: "Publicando...",
    loadingStories: "Cargando historias de la base de datos...",
    noStoriesAdmin: "No se encontraron historias en la base de datos.",
    editStory: "Editar Historia",
    saveChanges: "Guardar Cambios",
    cancel: "Cancelar",
    deleteLabel: "Eliminar",
    editLabel: "Editar",
    commentsPending: "Pendientes",
    commentsApproved: "Aprobados",
    commentsRejected: "Rechazados/Ocultos",
    all: "Todos",
    updateList: "Actualizar Lista",
    editTitle: "Título",
    editAuthor: "Autor",
    editTags: "Etiquetas (separadas por comas)",
    editTagsPlaceholder: "Romance, Fantasía, Drama",
    refresh: "Actualizar",
    loginWithGoogle: "Iniciar sesión con Google",
    adminAccess: "Acceso Admin",
    restrictedAccess: "Acceso Restringido",
    restrictedAccessDesc: "Esta área es exclusiva para administradores de la biblioteca.",
    goToLibrary: "Ir a la Biblioteca",
    exitAccount: "Cerrar Sesión",
    emptyFieldsError: "El título y el autor no pueden estar vacíos.",
    storyUpdatedSuccess: "¡Historia actualizada con éxito!",
    storyDeletedSuccess: 'La historia "{title}" fue eliminada de la base de datos.',
    commentsApprovalTitle: "Moderación de Comentarios",
    approve: "Aprobar",
    reject: "Rechazar",
    hide: "Ocultar",
    noCommentsFound: "No se encontraron comentarios.",
    statusLabel: "Estado",
    userLabel: "Usuario",
    textLabel: "Comentario",
    ratingLabel: "Calificación",
    actionsLabel: "Acciones",
    any: "Cualquiera",
    startingFiles: "Iniciando archivos...",
    initialPrep: "Preparación inicial",
    coverProcessing: "Procesamiento de la imagen de portada",
    docxProcessing: "Procesamiento de documento Word (.docx)",
    docxInvalid: "El documento de Word leído no tiene páginas válidas.",
    tagGeneration: "Generación automática de géneros y etiquetas",
    dbCreation: "Creación de registro principal en la base de datos",
    dbPageSending: "Envío de páginas en la base de datos ({end} de {total})",
    publishSuccess: "¡Publicación completada con éxito!",
    stageFailed: "Fallo en la etapa: {stage}",
    realTimeError: "Error en Tiempo Real ({stage})",
    errorProcess: "Error durante el proceso: ",
    errorUpdatingStory: "Error al actualizar la historia: ",
    errorDeletingStory: "Error al eliminar la historia: ",
    errorUpdatingCommentStatus: "Error al actualizar el estado del comentario.",
    loginFailed: "El inicio de sesión falló",
    unknownAuthor: "Autor desconocido",
    recentDate: "Fecha reciente",
    approved: "Aprobado",
    pending: "Pendiente",
    rejected: "Rechazado",
    pages: "páginas",
    publishedAt: "Publicado el: {date}",
    confirmDeleteTitle: "Confirmar Eliminación",
    irreversibleAction: "Esta acción es irreversible",
    confirmDeletePrompt: "¿Está seguro de que desea eliminar la historia {title} permanentemente de la base de datos?",
    confirmDeleteWarning: "Esta acción eliminará la historia, todas sus páginas y todas las reseñas de la base de datos.",
    yesDelete: "Sí, Eliminar",
    noCommentsCategory: "Sin comentarios en esta categoría.",
    loadingComments: "Cargando comentarios para moderación..."
  },
  en: {
    // Navigation / Header / Footer
    library: "Library",
    admin: "Admin",
    toggleTheme: "Toggle light and dark mode",
    login: "Log In",
    register: "Register",
    logout: "Log Out",
    profile: "My Profile",
    version: "Version",
    online: "Online",
    bthDigital: "BTH Digital",
    bthLibrary: "BTH Library",
    language: "Language",
    
    // Home Page
    archive: "Collection",
    welcomeUser: "Welcome, {name}. Explore the digital collection.",
    exploreArchive: "Explore incredible stories and save your progress.",
    exploreStories: "Explore incredible stories and save your progress.",
    history: "History",
    favorites: "Favorites",
    searchPlaceholder: "Search title, author or genre...",
    mostRecent: "Most Recent",
    mostPopular: "Most Popular",
    noStoriesFound: "No stories found.",
    noFavoritesFound: "You haven't added any stories to favorites yet.",
    noHistoryFound: "Your reading history is empty.",
    continueReading: "Continue",
    by: "By",
    publishedOn: "Published on",
    pageOf: "Page {page} of {total}",
    readTime: "min read",
    
    // Reader Page
    backToLibrary: "Back to Library",
    readingResumed: "Reading Resumed",
    readingRestored: "Your reading was automatically restored on page {page}.",
    restartPage1: "Restart (Page 1)",
    goTo: "Go to:",
    loadingPage: "Loading page...",
    previous: "Previous",
    next: "Next",
    approvedComments: "Approved Comments",
    endOfStory: "End of Story",
    enjoyedReading: "Did you enjoy the reading? Leave your review.",
    reviewSent: "Review Submitted!",
    reviewSavedPending: "Your review has been registered. If you included a comment, it will be moderated before being published.",
    yourRating: "Your Rating",
    commentLabel: "Comment (Subject to moderation)",
    commentPlaceholder: "Write your opinion about the story...",
    moderationNotice: "Comments are reviewed by the administrator before becoming publicly visible.",
    sending: "Sending...",
    submitReview: "Submit Review",
    loadingStory: "Opening story...",
    storyNotFound: "Story not found.",
    reader: "Reader",
    errorSubmitReview: "Error submitting review.",
    pageNotFound: "Page not found.",
    errorLoadingPage: "Error loading page.",
    
    // Auth Modal
    changePassword: "Change Password",
    myProfile: "My Profile",
    currentPassword: "Current Password",
    newPassword: "New Password",
    newPasswordPlaceholder: "Minimum 6 characters",
    currentPasswordPlaceholder: "Your current password",
    saveNewPassword: "Save New Password",
    updating: "Updating...",
    enterLibrary: "Enter the Library",
    createAccount: "Create an Account",
    recoverPassword: "Recover Password",
    accessFavorites: "Access your favorites and track your reading progress.",
    signupToSave: "Sign up to save your stories and reviews.",
    forgotPasswordInstructions: "Enter your email to set a new password.",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    confirmPasswordPlaceholder: "Enter password again",
    nameLabel: "Full Name",
    namePlaceholder: "Your name",
    forgotPasswordLink: "Forgot my password",
    alreadyHaveAccount: "Already have an account?",
    dontHaveAccount: "Don't have an account yet?",
    forgotPasswordStep1Instructions: "Enter your account email to reset password directly on the platform.",
    passwordStrengthTip: "Tip: Use letters, numbers and at least 6 characters for a strong password.",
    passwordMismatch: "The passwords entered do not match.",
    passwordMinLength: "The password must be at least 6 characters.",
    fillAllFields: "Fill in the current password and the new password.",
    passwordChangedSuccess: "Your password has been changed successfully!",
    successLabel: "Success",
    errorLabel: "Error",
    forgotStep3Success: "Your password has been successfully reset on the site. You can now log in with your new credentials.",
    forgotStep3Title: "Password Reset!",
    forgotStep3Button: "Go to Login",
    entering: "Logging in...",
    creatingAccount: "Creating Account...",
    checking: "Verifying...",
    saving: "Saving...",
    passwordGuideline: "Your password must contain at least 6 characters.",
    passwordGuidelineStrength: "Create a secure password containing at least 6 characters, combining letters and numbers.",
    passwordGuidelineStrengthTitle: "Strong Password Guidelines",
    forgotStep1InstructionsEmail: "Enter your account email to reset your password directly on the platform.",
    
    // Admin Page
    adminPanel: "Admin Panel",
    publish: "Publish",
    manage: "Manage",
    moderateComments: "Moderate Comments",
    storyTitle: "Story Title",
    storyTitlePlaceholder: "Ex: The Secret of the Stars",
    authorPlaceholder: "Ex: William Shakespeare",
    publishDate: "Publication Date",
    coverImageLabel: "Cover Image (JPEG/PNG)",
    coverImagePlaceholder: "Click to select cover",
    storyFileLabel: "Story File (DOCX)",
    storyFilePlaceholder: "Click to select DOCX",
    authorizeDrive: "Authorize Google Drive for Upload",
    publishStory: "Publish Story",
    publishing: "Publishing...",
    loadingStories: "Loading stories from the database...",
    noStoriesAdmin: "No stories found in the database.",
    editStory: "Edit Story",
    saveChanges: "Save Changes",
    cancel: "Cancel",
    deleteLabel: "Delete",
    editLabel: "Edit",
    commentsPending: "Pending",
    commentsApproved: "Approved",
    commentsRejected: "Rejected/Hidden",
    all: "All",
    updateList: "Update List",
    editTitle: "Title",
    editAuthor: "Author",
    editTags: "Tags (separated by comma)",
    editTagsPlaceholder: "Romance, Fantasy, Drama",
    refresh: "Refresh",
    loginWithGoogle: "Log in with Google",
    adminAccess: "Admin Access",
    restrictedAccess: "Restricted Access",
    restrictedAccessDesc: "This area is exclusive for library administrators.",
    goToLibrary: "Go to Library",
    exitAccount: "Log Out",
    emptyFieldsError: "The title and author cannot be empty.",
    storyUpdatedSuccess: "Story updated successfully!",
    storyDeletedSuccess: 'The story "{title}" was deleted from the database.',
    commentsApprovalTitle: "Comments Moderation",
    approve: "Approve",
    reject: "Reject",
    hide: "Hide",
    noCommentsFound: "No comments found.",
    statusLabel: "Status",
    userLabel: "User",
    textLabel: "Comment",
    ratingLabel: "Rating",
    actionsLabel: "Actions",
    any: "Any",
    startingFiles: "Starting files...",
    initialPrep: "Initial preparation",
    coverProcessing: "Cover image processing",
    docxProcessing: "Word document (.docx) processing",
    docxInvalid: "The read Word document does not have valid pages.",
    tagGeneration: "Automatic generation of genres and tags",
    dbCreation: "Creation of main record in the database",
    dbPageSending: "Sending pages in the database ({end} of {total})",
    publishSuccess: "Publishing completed successfully!",
    stageFailed: "Failed at stage: {stage}",
    realTimeError: "Real-Time Error ({stage})",
    errorProcess: "Error during process: ",
    errorUpdatingStory: "Error updating story: ",
    errorDeletingStory: "Error deleting story: ",
    errorUpdatingCommentStatus: "Error updating comment status.",
    loginFailed: "Login failed",
    unknownAuthor: "Unknown author",
    recentDate: "Recent date",
    approved: "Approved",
    pending: "Pending",
    rejected: "Rejected",
    pages: "pages",
    publishedAt: "Published on: {date}",
    confirmDeleteTitle: "Confirm Deletion",
    irreversibleAction: "This action is irreversible",
    confirmDeletePrompt: "Are you sure you want to delete the story {title} permanently from the database?",
    confirmDeleteWarning: "This action will remove the story, all its pages, and all reviews from the database.",
    yesDelete: "Yes, Delete",
    noCommentsCategory: "No comments in this category.",
    loadingComments: "Loading comments for moderation..."
  },
  id: {
    // Navigation / Header / Footer
    library: "Perpustakaan",
    admin: "Admin",
    toggleTheme: "Ubah mode terang dan gelap",
    login: "Masuk",
    register: "Daftar",
    logout: "Keluar Akun",
    profile: "Profil Saya",
    version: "Versi",
    online: "Online",
    bthDigital: "BTH Digital",
    bthLibrary: "Perpustakaan BTH",
    language: "Bahasa",
    
    // Home Page
    archive: "Koleksi",
    welcomeUser: "Selamat datang, {name}. Jelajahi koleksi digital.",
    exploreArchive: "Jelajahi cerita luar biasa dan simpan progres membaca Anda.",
    exploreStories: "Jelajahi cerita luar biasa dan simpan progres membaca Anda.",
    history: "Riwayat",
    favorites: "Favorit",
    searchPlaceholder: "Cari judul, penulis, atau genre...",
    mostRecent: "Terbaru",
    mostPopular: "Terpopuler",
    noStoriesFound: "Cerita tidak ditemukan.",
    noFavoritesFound: "Anda belum menambahkan cerita ke favorit.",
    noHistoryFound: "Riwayat membaca Anda kosong.",
    continueReading: "Lanjutkan",
    by: "Oleh",
    publishedOn: "Diterbitkan pada",
    pageOf: "Hal. {page} dari {total}",
    readTime: "menit bacaan",
    
    // Reader Page
    backToLibrary: "Kembali ke Perpustakaan",
    readingResumed: "Melanjutkan Membaca",
    readingRestored: "Membaca Anda secara otomatis dipulihkan pada halaman {page}.",
    restartPage1: "Mulai Ulang (Hal. 1)",
    goTo: "Pergi ke:",
    loadingPage: "Memuat halaman...",
    previous: "Sebelumnya",
    next: "Berikutnya",
    approvedComments: "Komentar yang Disetujui",
    endOfStory: "Akhir Cerita",
    enjoyedReading: "Apakah Anda menikmati cerita ini? Tinggalkan ulasan Anda.",
    reviewSent: "Ulasan Terkirim!",
    reviewSavedPending: "Ulasan Anda telah terdaftar. Jika Anda menyertakan komentar, komentar tersebut akan dimoderasi sebelum diterbitkan.",
    yourRating: "Nilai Anda",
    commentLabel: "Komentar (Subjek moderasi)",
    commentPlaceholder: "Tulis pendapat Anda tentang cerita ini...",
    moderationNotice: "Komentar akan ditinjau oleh administrator sebelum ditampilkan secara publik.",
    sending: "Mengirim...",
    submitReview: "Kirim Ulasan",
    loadingStory: "Membuka cerita...",
    storyNotFound: "Cerita tidak ditemukan.",
    reader: "Pembaca",
    errorSubmitReview: "Gagal mengirim ulasan.",
    pageNotFound: "Halaman tidak ditemukan.",
    errorLoadingPage: "Gagal memuat halaman.",
    
    // Auth Modal
    changePassword: "Ubah Kata Sandi",
    myProfile: "Profil Saya",
    currentPassword: "Kata Sandi Sekarang",
    newPassword: "Kata Sandi Baru",
    newPasswordPlaceholder: "Minimal 6 karakter",
    currentPasswordPlaceholder: "Kata sandi sekarang Anda",
    saveNewPassword: "Simpan Kata Sandi Baru",
    updating: "Memperbarui...",
    enterLibrary: "Masuk Perpustakaan",
    createAccount: "Buat Akun",
    recoverPassword: "Pulihkan Kata Sandi",
    accessFavorites: "Akses favorit Anda dan lacak progres membaca Anda.",
    signupToSave: "Daftar untuk menyimpan cerita dan ulasan Anda.",
    forgotPasswordInstructions: "Masukkan email Anda untuk menyetel kata sandi baru.",
    email: "Email",
    password: "Kata Sandi",
    confirmPassword: "Konfirmasi Kata Sandi",
    confirmPasswordPlaceholder: "Masukkan kata sandi lagi",
    nameLabel: "Nama Lengkap",
    namePlaceholder: "Nama Anda",
    forgotPasswordLink: "Lupa kata sandi",
    alreadyHaveAccount: "Sudah punya akun?",
    dontHaveAccount: "Belum punya akun?",
    forgotPasswordStep1Instructions: "Masukkan email akun Anda untuk menyetel ulang kata sandi langsung di platform.",
    passwordStrengthTip: "Tips: Gunakan huruf, angka, dan minimal 6 karakter untuk kata sandi yang kuat.",
    passwordMismatch: "Kata sandi yang dimasukkan tidak cocok.",
    passwordMinLength: "Kata sandi harus minimal 6 karakter.",
    fillAllFields: "Isi kata sandi saat ini dan kata sandi baru.",
    passwordChangedSuccess: "Kata sandi Anda berhasil diubah!",
    successLabel: "Sukses",
    errorLabel: "Kesalahan",
    forgotStep3Success: "Kata sandi Anda berhasil disetel ulang di situs. Anda sekarang dapat masuk dengan kredensial baru Anda.",
    forgotStep3Title: "Kata Sandi Disetel Ulang!",
    forgotStep3Button: "Pergi ke Masuk",
    entering: "Masuk...",
    creatingAccount: "Membuat Akun...",
    checking: "Memverifikasi...",
    saving: "Menyimpan...",
    passwordGuideline: "Kata sandi Anda harus berisi minimal 6 karakter.",
    passwordGuidelineStrength: "Buat kata sandi aman yang berisi minimal 6 karakter, menggabungkan huruf dan angka.",
    passwordGuidelineStrengthTitle: "Panduan Kata Sandi Kuat",
    forgotStep1InstructionsEmail: "Masukkan email akun Anda untuk menyetel ulang kata sandi Anda langsung di platform.",
    
    // Admin Page
    adminPanel: "Panel Admin",
    publish: "Terbitkan",
    manage: "Kelola",
    moderateComments: "Moderat Komentar",
    storyTitle: "Judul Cerita",
    storyTitlePlaceholder: "Contoh: Rahasia Bintang",
    authorPlaceholder: "Contoh: Pramoedya Ananta Toer",
    publishDate: "Tanggal Terbit",
    coverImageLabel: "Gambar Sampul (JPEG/PNG)",
    coverImagePlaceholder: "Klik untuk memilih sampul",
    storyFileLabel: "File Cerita (DOCX)",
    storyFilePlaceholder: "Klik untuk memilih DOCX",
    authorizeDrive: "Otorisasi Google Drive untuk Unggah",
    publishStory: "Terbitkan Cerita",
    publishing: "Menerbitkan...",
    loadingStories: "Memuat cerita dari database...",
    noStoriesAdmin: "Cerita tidak ditemukan di database.",
    editStory: "Edit Cerita",
    saveChanges: "Simpan Perubahan",
    cancel: "Batal",
    deleteLabel: "Hapus",
    editLabel: "Edit",
    commentsPending: "Tertunda",
    commentsApproved: "Disetujui",
    commentsRejected: "Ditolak/Disembunyikan",
    all: "Semua",
    updateList: "Perbarui Daftar",
    editTitle: "Judul",
    editAuthor: "Penulis",
    editTags: "Tag (dipisahkan dengan koma)",
    editTagsPlaceholder: "Romansa, Fantasi, Drama",
    refresh: "Segarkan",
    loginWithGoogle: "Masuk dengan Google",
    adminAccess: "Akses Admin",
    restrictedAccess: "Akses Terbatas",
    restrictedAccessDesc: "Area ini eksklusif untuk administrator perpustakaan.",
    goToLibrary: "Pergi ke Perpustakaan",
    exitAccount: "Keluar Akun",
    emptyFieldsError: "Judul dan penulis tidak boleh kosong.",
    storyUpdatedSuccess: "Cerita berhasil diperbarui!",
    storyDeletedSuccess: 'Cerita "{title}" telah dihapus dari database.',
    commentsApprovalTitle: "Moderasi Komentar",
    approve: "Setujui",
    reject: "Tolak",
    hide: "Sembunyikan",
    noCommentsFound: "Komentar tidak ditemukan.",
    statusLabel: "Status",
    userLabel: "Pengguna",
    textLabel: "Komentar",
    ratingLabel: "Penilaian",
    actionsLabel: "Tindakan",
    any: "Semua",
    startingFiles: "Memulai file...",
    initialPrep: "Persiapan awal",
    coverProcessing: "Pemrosesan gambar sampul",
    docxProcessing: "Pemrosesan dokumen Word (.docx)",
    docxInvalid: "Dokumen Word yang dibaca tidak memiliki halaman yang valid.",
    tagGeneration: "Pembuatan otomatis genre dan tag",
    dbCreation: "Pembuatan rekaman utama di database",
    dbPageSending: "Mengirim halaman di database ({end} dari {total})",
    publishSuccess: "Penerbitan berhasil diselesaikan!",
    stageFailed: "Gagal pada tahap: {stage}",
    realTimeError: "Kesalahan Real-Time ({stage})",
    errorProcess: "Kesalahan selama proses: ",
    errorUpdatingStory: "Gagal memperbarui cerita: ",
    errorDeletingStory: "Gagal menghapus cerita: ",
    errorUpdatingCommentStatus: "Gagal memperbarui status komentar.",
    loginFailed: "Login gagal",
    unknownAuthor: "Penulis tidak diketahui",
    recentDate: "Tanggal baru-baru ini",
    approved: "Disetujui",
    pending: "Tertunda",
    rejected: "Ditolak",
    pages: "halaman",
    publishedAt: "Diterbitkan pada: {date}",
    confirmDeleteTitle: "Konfirmasi Penghapusan",
    irreversibleAction: "Tindakan ini tidak dapat dibatalkan",
    confirmDeletePrompt: "Apakah Anda yakin ingin menghapus cerita {title} secara permanen dari database?",
    confirmDeleteWarning: "Tindakan ini akan menghapus cerita, semua halamannya, dan semua ulasan dari database.",
    yesDelete: "Ya, Hapus",
    noCommentsCategory: "Tidak ada komentar dalam kategori ini.",
    loadingComments: "Memuat komentar untuk moderasi..."
  }
} as const;

export type TranslationKey = keyof typeof translations.pt;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey, replace?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType>({} as LanguageContextType);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("site_language");
    if (saved === "pt" || saved === "es" || saved === "en" || saved === "id") {
      return saved as Language;
    }
    return "pt";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("site_language", lang);
  };

  const t = (key: TranslationKey, replace?: Record<string, string | number>): string => {
    const currentTranslations = translations[language] || translations.pt;
    let text = currentTranslations[key] || translations.pt[key] || String(key);
    
    if (replace) {
      Object.entries(replace).forEach(([k, v]) => {
        text = text.replace(`{${k}}`, String(v));
      });
    }
    
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
