import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "pt" | "es" | "en" | "id";

export const translations = {
  pt: {
    // Navigation / Header / Footer
    library: "Acervo",
    admin: "Área do Autor",
    toggleTheme: "Alternar modo claro e escuro",
    login: "Entrar",
    register: "Cadastrar",
    logout: "Sair da Conta",
    profile: "Meu Perfil",
    version: "Versão",
    online: "Online",
    bthDigital: "INK Digital",
    bthLibrary: "Acervo",
    appBrand: "INKORA",
    language: "Idioma",
    
    // Home Page
    archive: "Acervo",
    welcomeUser: "Bem-vindo(a), {name}. Explore o acervo digital.",
    exploreArchive: "Explore histórias incríveis e salve sua leitura.",
    exploreStories: "Explore histórias incríveis e salve sua leitura.",
    history: "Histórico",
    favorites: "Favoritos",
    searchPlaceholder: "Buscar título, autor ou gênero...",
    mostRecent: "Mais Recentes",
    mostPopular: "Mais Populares",
    noStoriesFound: "Nenhuma história encontrada.",
    noFavoritesFound: "Você ainda não adicionou histórias aos favoritos.",
    noHistoryFound: "Seu histórico de leitura está vazio.",
    continueReading: "Continuar",
    by: "Por",
    publishedOn: "Publicado em",
    pageOf: "Pág. {page} de {total}",
    readTime: "min de leitura",
    
    // Reader Page
    backToLibrary: "Voltar à Biblioteca",
    readingResumed: "Leitura Retomada",
    readingRestored: "Sua leitura foi restaurada automaticamente na página {page}.",
    restartPage1: "Reiniciar (Pág. 1)",
    goTo: "Ir para:",
    loadingPage: "Carregando página...",
    previous: "Anterior",
    next: "Próxima",
    approvedComments: "Comentários Aprovados",
    endOfStory: "Fim da História",
    enjoyedReading: "Gostou da leitura? Deixe sua avaliação.",
    reviewSent: "Avaliação Enviada!",
    reviewSavedPending: "Sua avaliação foi registrada. Caso tenha incluído um comentário, ele passará pela moderação antes de ser publicado.",
    yourRating: "Sua Nota",
    commentLabel: "Comentário (Sujeito à moderação)",
    commentPlaceholder: "Escreva sua opinião sobre a história...",
    moderationNotice: "Os comentários são revisados pelo administrador antes de ficarem visíveis publicamente.",
    sending: "Enviando...",
    submitReview: "Enviar Avaliação",
    loadingStory: "Abrindo história...",
    storyNotFound: "História não encontrada.",
    reader: "Leitor",
    errorSubmitReview: "Erro ao enviar avaliação.",
    pageNotFound: "Página não encontrada.",
    errorLoadingPage: "Erro ao carregar página.",
    
    // Eye Comfort
    eyeComfort: "Conforto Ocular",
    yellowFilter: "Filtro Amarelo",
    filterIntensity: "Intensidade do Filtro",
    eyeComfortDescription: "Filtro amarelo anti-fadiga para leitura suave",
    off: "Desligado",
    
    // Auth Modal
    changePassword: "Alterar Senha",
    myProfile: "Meu Perfil",
    currentPassword: "Senha Atual",
    newPassword: "Nova Senha",
    newPasswordPlaceholder: "Mínimo de 6 caracteres",
    currentPasswordPlaceholder: "Sua senha atual",
    saveNewPassword: "Salvar Nova Senha",
    updating: "Atualizando...",
    enterLibrary: "Entrar na Biblioteca",
    createAccount: "Criar uma Conta",
    recoverPassword: "Recuperar Senha",
    accessFavorites: "Acesse seus favoritos e acompanhe seu progresso de leitura.",
    signupToSave: "Cadastre-se para salvar suas histórias e avaliações.",
    forgotPasswordInstructions: "Informe seu e-mail para definir uma nova senha.",
    email: "E-mail",
    password: "Senha",
    confirmPassword: "Confirmar Senha",
    confirmPasswordPlaceholder: "Digite a senha novamente",
    nameLabel: "Nome Completo",
    namePlaceholder: "Seu nome",
    usernameLabel: "Nome de Usuário (@)",
    usernamePlaceholder: "seu_usuario",
    forgotPasswordLink: "Esqueci minha senha",
    alreadyHaveAccount: "Já tem uma conta?",
    dontHaveAccount: "Ainda não possui uma conta?",
    forgotPasswordStep1Instructions: "Informe o e-mail da sua conta para redefinir a senha diretamente na plataforma.",
    passwordStrengthTip: "Dica: Utilize letras, números e no mínimo 6 caracteres para uma senha forte.",
    passwordMismatch: "As senhas informadas não coincidem.",
    passwordMinLength: "A senha deve ter no mínimo 6 caracteres.",
    fillAllFields: "Preencha a senha atual e a nova senha.",
    passwordChangedSuccess: "Sua senha foi alterada com sucesso!",
    successLabel: "Sucesso",
    errorLabel: "Erro",
    forgotStep3Success: "Sua senha foi redefinida com sucesso diretamente no site. Você já pode entrar com suas novas credenciais.",
    forgotStep3Title: "Senha Redefinida!",
    forgotStep3Button: "Ir para o Login",
    entering: "Entrando...",
    creatingAccount: "Criando Conta...",
    checking: "Verificando...",
    saving: "Salvando...",
    passwordGuideline: "Sua senha deve conter pelo menos 6 caracteres.",
    passwordGuidelineStrength: "Crie uma senha segura contendo no mínimo 6 caracteres, combinando letras e números.",
    passwordGuidelineStrengthTitle: "Orientação para Senha Forte",
    forgotStep1InstructionsEmail: "Informe o e-mail da sua conta para redefinir a senha diretamente na plataforma.",
    
    // Admin Page
    adminPanel: "Painel do Autor",
    publish: "Publicar",
    manage: "Gerenciar",
    moderateComments: "Moderar Comentários",
    superadmin: "Administração Master",
    writerNoticeFullScreen: "O editor abrirá em uma nova página em tela cheia para maior conforto.",
    useShortName: "Usar: {name}",
    newCoverOptional: "(Nova)",
    storyTitle: "Título da História",
    storyTitlePlaceholder: "Ex: O Segredo das Estrelas",
    authorPlaceholder: "Ex: Machado de Assis",
    publishDate: "Data de Publicação",
    coverImageLabel: "Imagem de Capa (JPEG/PNG)",
    coverImagePlaceholder: "Clique para selecionar a capa",
    storyFileLabel: "Arquivo da História (DOCX)",
    storyFilePlaceholder: "Clique para selecionar o DOCX",
    authorizeDrive: "Autorizar Google Drive para Upload",
    publishStory: "Publicar História",
    publishing: "Publicando...",
    loadingStories: "Carregando histórias do banco de dados...",
    noStoriesAdmin: "Nenhuma história encontrada no banco de dados.",
    editStory: "Editar História",
    saveChanges: "Salvar Alterações",
    cancel: "Cancelar",
    deleteLabel: "Apagar",
    editLabel: "Editar",
    commentsPending: "Pendentes",
    commentsApproved: "Aprovados",
    commentsRejected: "Rejeitados/Ocultos",
    all: "Todos",
    updateList: "Atualizar Lista",
    editTitle: "Título",
    editAuthor: "Autor",
    editTags: "Tags (separadas por vírgula)",
    editTagsPlaceholder: "Romance, Fantasia, Drama",
    refresh: "Atualizar",
    loginWithGoogle: "Entrar com Google",
    adminAccess: "Acesso de Autor",
    restrictedAccess: "Acesso Restrito",
    restrictedAccessDesc: "Esta área é exclusiva para autores da biblioteca.",
    goToLibrary: "Ir para a Biblioteca",
    exitAccount: "Sair da Conta",
    emptyFieldsError: "O título e o autor não podem ficar vazios.",
    storyUpdatedSuccess: "História atualizada com sucesso!",
    storyDeletedSuccess: 'A história "{title}" foi apagada do banco de dados.',
    commentsApprovalTitle: "Moderação de Comentários",
    approve: "Aprovar",
    reject: "Rejeitar",
    hide: "Ocultar",
    noCommentsFound: "Nenhum comentário encontrado.",
    statusLabel: "Status",
    userLabel: "Usuário",
    textLabel: "Comentário",
    ratingLabel: "Avaliação",
    actionsLabel: "Ações",
    any: "Qualquer",
    startingFiles: "Iniciando arquivos...",
    initialPrep: "Preparação inicial",
    coverProcessing: "Processamento da imagem de capa",
    docxProcessing: "Processamento do documento Word (.docx)",
    docxInvalid: "O documento Word lido não possui páginas válidas.",
    tagGeneration: "Geração automática de gêneros e tags",
    dbCreation: "Criação do registro principal no banco de dados",
    dbPageSending: "Envio das páginas no banco de dados ({end} de {total})",
    publishSuccess: "Publicação concluída com sucesso!",
    stageFailed: "Falha na etapa: {stage}",
    realTimeError: "Erro em Tempo Real ({stage})",
    errorProcess: "Erro durante o processo: ",
    errorUpdatingStory: "Erro ao atualizar história: ",
    errorDeletingStory: "Erro ao apagar história: ",
    errorUpdatingCommentStatus: "Erro ao atualizar status do comentário.",
    loginFailed: "Login falhou",
    unknownAuthor: "Autor desconhecido",
    recentDate: "Data recente",
    approved: "Aprovado",
    pending: "Pendente",
    rejected: "Rejeitado",
    pages: "páginas",
    publishedAt: "Publicado em: {date}",
    confirmDeleteTitle: "Confirmar Exclusão",
    irreversibleAction: "Esta ação é irreversível",
    confirmDeletePrompt: "Tem certeza de que deseja apagar a história {title} permanentemente do banco de dados?",
    confirmDeleteWarning: "Esta ação removerá a história, todas as suas páginas e todas as avaliações do banco de dados.",
    yesDelete: "Sim, Apagar",
    noCommentsCategory: "Nenhum comentário nesta categoria.",
    loadingComments: "Carregando comentários para moderação...",
    editInSite: "Escrever",
    writeOnSite: "Escrever no Site",
    uploadDocxFile: "Importar DOCX",
    saveDraft: "Salvar como Rascunho",
    publishNow: "Publicar História",
    draft: "Rascunho",
    drafts: "Rascunhos",
    published: "Publicados",
    isDraftBadge: "RASCUNHO",
    isPublishedBadge: "PUBLICADO",
    editorTitle: "Editor de História",
    formatTitle: "Título Principal",
    formatSubtitle: "Subtítulo",
    formatParagraph: "Texto Normal",
    insertPageBreak: "Quebra de Página",
    autoPageBreak: "Quebra Automática de Página",
    wordsPerPage: "Palavras por página",
    pagesCount: "{count} página(s)",
    editInWriter: "Editar Texto no Site",
    publishDraftConfirm: "Deseja publicar este rascunho agora?",
    draftSavedSuccess: "Rascunho salvo com sucesso no banco de dados!",
    draftPublishedSuccess: "História publicada com sucesso!",
    filterStatus: "Filtrar por Status",
    allStatus: "Todos os Status",
    draftModeNotice: "Modo Rascunho - Visualização do Autor",
    bold: "Negrito",
    italic: "Itálico",
    underline: "Sublinhado",
    strikethrough: "Tachado",
    alignLeft: "Esquerda",
    alignCenter: "Centralizar",
    alignRight: "Direita",
    alignJustify: "Justificar",
    bulletList: "Marcadores",
    numberList: "Numeração",
    quote: "Citação",
    typeContentHere: "Escreva sua história aqui...",
    pagesGenerated: "Páginas geradas",

    // Advanced Typographic Accessibility & Themes
    openDyslexic: "OpenDyslexic (Acessibilidade)",
    fontFamily: "Fonte da Leitura",
    serifFont: "Serifada Elegante",
    sansFont: "Sem Serifa Moderna",
    dyslexicFont: "OpenDyslexic (Dislexia)",
    marginSize: "Margens",
    narrowMargin: "Estreita",
    normalMargin: "Padrão",
    wideMargin: "Larga",
    lineSpacing: "Entrelinhas",
    compactLine: "Compacto (1.4)",
    relaxedLine: "Aconchegante (1.8)",
    looseLine: "Expandido (2.2)",
    readingTheme: "Tema do Leitor",
    sepiaTheme: "Sépia Acolhedor",
    lightTheme: "Claro Padrão",
    darkTheme: "Escuro Noturno",

    // Analytics & Metrics
    analyticsDashboard: "Análise e Métricas",
    avgReadingTime: "Tempo Médio de Leitura",
    completionRate: "Taxa de Retenção",
    totalViews: "Visualizações Totais",
    topPages: "Capítulos Mais Lidos",
    retentionRate: "Conclusão de Leitura",
    readingMetrics: "Métricas dos Leitores",
    readerEngagement: "Engajamento",
    authorMetrics: "Métricas de Desempenho",

    // Scheduled Release
    scheduledRelease: "Lançamento Agendado",
    scheduledReleaseAt: "Data/Hora de Lançamento",
    releaseScheduledFor: "Agendado para {date}",
    scheduledStatus: "Agendados",
    notYetReleased: "História ainda não lançada publicamente.",
    isScheduledBadge: "AGENDADO",

    // Multi-criteria Ratings
    plotRating: "Enredo e Trama",
    characterRating: "Desenvolvimento de Personagens",
    writingRating: "Qualidade da Escrita",
    overallRating: "Nota Geral",
    criteriaBreakdown: "Avaliação Detalhada por Critério",

    // Playlists / Reading Lists
    playlists: "Playlists de Livros",
    createPlaylist: "Criar Lista de Leitura",
    playlistTitle: "Título da Playlist",
    playlistDescription: "Descrição",
    addToPlaylist: "Adicionar à Lista",
    removeFromPlaylist: "Remover da Lista",
    publicPlaylists: "Coleções Públicas",
    myPlaylists: "Minhas Listas",
    emptyPlaylist: "Nenhuma história nesta lista.",
    isPublicList: "Lista Pública",
    managePlaylist: "Gerenciar Playlist",
    addStories: "Adicionar Histórias",
    editPlaylist: "Editar Playlist",
    deletePlaylist: "Excluir Playlist",
    selectStoriesToAdd: "Selecione histórias para incluir nesta playlist:",
    storiesCount: "{count} histórias",

    // Achievements & Badges
    achievements: "Conquistas e Emblemas",
    badges: "Medalhas",
    myAchievements: "Minhas Conquistas",
    unlockedAt: "Desbloqueado em",
    progress: "Progresso",

    // Offline Mode
    offlineMode: "Modo Offline",
    downloadForOffline: "Baixar para Ler Offline",
    downloadedOffline: "Salvo no Dispositivo",
    removeOffline: "Remover Download",
    offlineAvailable: "Disponível Offline",
    savedOfflineStories: "Histórias Baixadas",

    // Bookmarks & Private Notes
    bookmarks: "Marcadores",
    privateNotes: "Anotações Privadas",
    addBookmark: "Marcar Página",
    addNote: "Adicionar Nota",
    addNoteForPage: "Nova anotação na Página {page}",
    yourNotes: "Minhas Notas nesta História",
    notePlaceholder: "Escreva uma reflexão ou anotação pessoal...",
    saveNote: "Salvar Nota",
    jumpToPage: "Ir para Pág. {page}",
    bookmarkSaved: "Página marcada com sucesso!",
    backToAdmin: "Voltar ao Painel do Autor",
    pendingAutoSave: "Pendente (30s)",
    autoSaveInterval: "Auto-salvamento a cada 30s",
    autoSaving: "Salvando...",
    savingDraft: "Salvando rascunho...",
    draftSavedAt: "Rascunho salvo às {time}",
    autoSaveIn: "Auto-salvamento em 30s",
    useMyName: "Usar meu Nome: {name}",
    useMyUsername: "Usar meu @Usuário: @{username}",
    useUsernameOnly: "Usar meu Usuário: {username}",
    clearSchedule: "Limpar Agendamento",
    previewPages: "Pré-visualizar Páginas",
    readerPreview: "Pré-visualização do Leitor",
    emptyPage: "Página vazia",
    pageBreak: "Quebra de Página",
    pageBreakMarker: "--- Quebra de Página (Pág. {page}) ---",
    pageBreakMarkerSimple: "--- Quebra de Página ---",
    wordsCount: "{count} palavras",
    readTimeEstimate: "~{count} min leitura",
    deleteCommentText: "Apagar Texto",
    deleteAllComment: "Excluir Tudo",
    deleteCommentTextTitle: "Excluir apenas o texto",
    deleteCommentTextSubtitle: "A avaliação de estrelas será preservada",
    deleteCommentTextConfirm: "Tem certeza que deseja excluir o texto do comentário de {name} na obra {title}?",
    deleteCommentTextNotice: "O texto do comentário será apagado permanentemente. A nota de {rating} estrelas e a contagem geral de avaliações do livro não sofrerão alterações.",
    deleteAllCommentTitle: "Excluir avaliação completa",
    deleteAllCommentConfirm: "Tem certeza que deseja excluir toda a avaliação (texto e a nota de {rating} estrelas) de {name} na obra {title}?",
    deleteAllCommentNotice: "Esta ação removerá totalmente o comentário e as estrelas do banco de dados de forma definitiva.",
    activeReaders: "Leitores Ativos",
    estimatedTimePerSession: "Tempo estimado gasto por sessão de leitura",
    readingStartedSingular: "leitura iniciada",
    readingStartedPlural: "leituras iniciadas",
    completionRateNotice: "Taxa de conclusão até a página final",
    performanceByStory: "Desempenho por História",
    storyTableHead: "História",
    startsTableHead: "Inícios",
    avgProgressTableHead: "Progresso Médio",
    completionsTableHead: "Conclusões",
    overallRatingTableHead: "Nota Geral",
    pageSingular: "página",
    pagePlural: "páginas",
    retentionByPage: "Retenção por Página",
    retentionDescription: "Percentual de leitores que alcançaram ou superaram cada página do livro.",
    readersSingular: "leitor",
    readersPlural: "leitores",
    engagementAndReviews: "Engajamento e Avaliações",
    engagementDescription: "Estatísticas qualitativas extraídas das avaliações públicas deixadas por leitores.",
    avgOverallRating: "Nota Média Geral",
    totalReviews: "Total de Notas",
    totalRegisteredUsers: "Total de Usuários Cadastrados",
    totalFavoritesInSite: "Total de Favoritos no Site",
    authorRequests: "Solicitações de Autores",
    noRequestsPending: "Nenhuma solicitação pendente.",
    authorize: "Autorizar",
    noName: "Sem nome",
    processingMetrics: "Processando e compilando dados de leitura reais...",
    noReadingDataTitle: "Sem dados de leitura ainda",
    noReadingDataDesc: "As métricas de retenção e progresso são geradas automaticamente quando os leitores começam a ler as suas obras na biblioteca.",
    styleTab: "Estilo",
    formatTab: "Formato",
    alignTab: "Alinhar",
    extrasTab: "Extras",
    styleBold: "Negrito",
    styleItalic: "Itálico",
    styleUnderline: "Sublinhado",
    styleStrike: "Riscado",
    styleLeft: "Esquerda",
    styleCenter: "Centro",
    styleRight: "Direita",
    styleJustify: "Justificar",
    styleBullets: "Marcas",
    styleNumbers: "Números",
    styleQuote: "Citar",
    stylePage: "Pág",
    updateWord: "Atualizar",
    accountType: "Tipo de Conta",
    readerRole: "Leitor",
    authorRole: "Autor"
  },
  es: {
    // Navigation / Header / Footer
    library: "Acervo",
    admin: "Área de Autor",
    toggleTheme: "Alternar modo claro y oscuro",
    login: "Iniciar Sesión",
    register: "Registrarse",
    logout: "Cerrar Sesión",
    profile: "Mi Perfil",
    version: "Versión",
    online: "En línea",
    bthDigital: "INK Digital",
    bthLibrary: "Acervo",
    appBrand: "INKORA",
    language: "Idioma",
    
    // Home Page
    archive: "Colección",
    welcomeUser: "Bienvenido(a), {name}. Explora la colección digital.",
    exploreArchive: "Explora historias increíbles y guarda tu lectura.",
    exploreStories: "Explora historias increíbles y guarda tu lectura.",
    history: "Historial",
    favorites: "Favoritos",
    searchPlaceholder: "Buscar título, autor o género...",
    mostRecent: "Más Recientes",
    mostPopular: "Más Populares",
    noStoriesFound: "No se encontraron historias.",
    noFavoritesFound: "Aún no has añadido historias a tus favoritos.",
    noHistoryFound: "Tu historial de lectura está vacío.",
    continueReading: "Continuar",
    by: "Por",
    publishedOn: "Publicado el",
    pageOf: "Pág. {page} de {total}",
    readTime: "min de lectura",
    
    // Reader Page
    backToLibrary: "Volver a la Biblioteca",
    readingResumed: "Lectura Reanudada",
    readingRestored: "Tu lectura se restauró automáticamente en la página {page}.",
    restartPage1: "Reiniciar (Pág. 1)",
    goTo: "Ir a:",
    loadingPage: "Cargando página...",
    previous: "Anterior",
    next: "Siguiente",
    approvedComments: "Comentarios Aprobados",
    endOfStory: "Fin de la Historia",
    enjoyedReading: "¿Te gustó la lectura? Deja tu reseña.",
    reviewSent: "¡Reseña Enviada!",
    reviewSavedPending: "Tu reseña ha sido registrada. Si incluiste un comentario, pasará por moderación antes de ser publicado.",
    yourRating: "Tu Calificación",
    commentLabel: "Comentario (Sujeto a moderación)",
    commentPlaceholder: "Escribe tu opinión sobre la historia...",
    moderationNotice: "Los comentarios son revisados por el administrador antes de ser visibles públicamente.",
    sending: "Enviando...",
    submitReview: "Enviar Reseña",
    loadingStory: "Abriendo historia...",
    storyNotFound: "Historia no encontrada.",
    reader: "Lector",
    errorSubmitReview: "Error al enviar la reseña.",
    pageNotFound: "Página no encontrada.",
    errorLoadingPage: "Error al cargar la página.",
    
    // Eye Comfort
    eyeComfort: "Confort Ocular",
    yellowFilter: "Filtro Amarillo",
    filterIntensity: "Intensidad del Filtro",
    eyeComfortDescription: "Filtro amarillo anti-fatiga para lectura suave",
    off: "Desactivado",
    
    // Auth Modal
    changePassword: "Cambiar Contraseña",
    myProfile: "Mi Perfil",
    currentPassword: "Contraseña Actual",
    newPassword: "Nueva Contraseña",
    newPasswordPlaceholder: "Mínimo de 6 caracteres",
    currentPasswordPlaceholder: "Tu contraseña actual",
    saveNewPassword: "Guardar Nueva Contraseña",
    updating: "Actualizando...",
    enterLibrary: "Ingresar a la Biblioteca",
    createAccount: "Crear una Cuenta",
    recoverPassword: "Recuperar Contraseña",
    accessFavorites: "Accede a tus favoritos y sigue tu progreso de lectura.",
    signupToSave: "Regístrate para guardar tus historias y reseñas.",
    forgotPasswordInstructions: "Ingresa tu correo para definir una nueva contraseña.",
    email: "Correo electrónico",
    password: "Contraseña",
    confirmPassword: "Confirmar Contraseña",
    confirmPasswordPlaceholder: "Ingresa la contraseña de nuevo",
    nameLabel: "Nombre Completo",
    namePlaceholder: "Tu nombre",
    usernameLabel: "Nombre de Usuario (@)",
    usernamePlaceholder: "tu_usuario",
    forgotPasswordLink: "Olvidé mi contraseña",
    alreadyHaveAccount: "¿Ya tienes una cuenta?",
    dontHaveAccount: "¿Aún no tienes una cuenta?",
    forgotPasswordStep1Instructions: "Ingresa el correo de tu cuenta para restablecer la contraseña directamente en la plataforma.",
    passwordStrengthTip: "Consejo: Usa letras, números y al menos 6 caracteres para una contraseña fuerte.",
    passwordMismatch: "Las contraseñas ingresadas no coinciden.",
    passwordMinLength: "La contraseña debe tener al menos 6 caracteres.",
    fillAllFields: "Completa la contraseña actual y la nueva contraseña.",
    passwordChangedSuccess: "¡Tu contraseña ha sido cambiada con éxito!",
    successLabel: "Éxito",
    errorLabel: "Error",
    forgotStep3Success: "Tu contraseña ha sido restablecida con éxito en el sitio. Ya puedes iniciar sesión con tus nuevas credenciales.",
    forgotStep3Title: "¡Contraseña Restablecida!",
    forgotStep3Button: "Ir al Inicio de Sesión",
    entering: "Iniciando sesión...",
    creatingAccount: "Creando Cuenta...",
    checking: "Verificando...",
    saving: "Guardando...",
    passwordGuideline: "Tu contraseña debe contener al menos 6 caracteres.",
    passwordGuidelineStrength: "Crea una contraseña segura que contenga al menos 6 caracteres, combinando letras y números.",
    passwordGuidelineStrengthTitle: "Guía de Contraseña Fuerte",
    forgotStep1InstructionsEmail: "Ingresa el correo de tu cuenta para restablecer tu contraseña directamente en la plataforma.",
    
    // Admin Page
    adminPanel: "Panel de Autor",
    publish: "Publicar",
    manage: "Gestionar",
    moderateComments: "Moderar Comentarios",
    superadmin: "Administración Principal",
    writerNoticeFullScreen: "El editor se abrirá en una nueva página a pantalla completa para mayor comodidad.",
    useShortName: "Usar: {name}",
    newCoverOptional: "(Nueva)",
    storyTitle: "Título de la Historia",
    storyTitlePlaceholder: "Ej: El Secreto de las Estrellas",
    authorPlaceholder: "Ej: Miguel de Cervantes",
    publishDate: "Fecha de Publicación",
    coverImageLabel: "Imagen de Portada (JPEG/PNG)",
    coverImagePlaceholder: "Haz clic para seleccionar la portada",
    storyFileLabel: "Archivo de la Historia (DOCX)",
    storyFilePlaceholder: "Haz clic para seleccionar el DOCX",
    authorizeDrive: "Autorizar Google Drive para Subir",
    publishStory: "Publicar Historia",
    publishing: "Publicando...",
    loadingStories: "Cargando historias de la base de datos...",
    noStoriesAdmin: "No se encontraron historias en la base de datos.",
    editStory: "Editar Historia",
    saveChanges: "Guardar Cambios",
    cancel: "Cancelar",
    deleteLabel: "Eliminar",
    editLabel: "Editar",
    commentsPending: "Pendientes",
    commentsApproved: "Aprobados",
    commentsRejected: "Rechazados/Ocultos",
    all: "Todos",
    updateList: "Actualizar Lista",
    editTitle: "Título",
    editAuthor: "Autor",
    editTags: "Etiquetas (separadas por comas)",
    editTagsPlaceholder: "Romance, Fantasía, Drama",
    refresh: "Actualizar",
    loginWithGoogle: "Iniciar sesión con Google",
    adminAccess: "Acceso de Autor",
    restrictedAccess: "Acceso Restringido",
    restrictedAccessDesc: "Esta área es exclusiva para autores de la biblioteca.",
    goToLibrary: "Ir a la Biblioteca",
    exitAccount: "Cerrar Sesión",
    emptyFieldsError: "El título y el autor no pueden estar vacíos.",
    storyUpdatedSuccess: "¡Historia actualizada con éxito!",
    storyDeletedSuccess: 'La historia "{title}" fue eliminada de la base de datos.',
    commentsApprovalTitle: "Moderación de Comentarios",
    approve: "Aprobar",
    reject: "Rechazar",
    hide: "Ocultar",
    noCommentsFound: "No se encontraron comentarios.",
    statusLabel: "Estado",
    userLabel: "Usuario",
    textLabel: "Comentario",
    ratingLabel: "Calificación",
    actionsLabel: "Acciones",
    any: "Cualquiera",
    startingFiles: "Iniciando archivos...",
    initialPrep: "Preparación inicial",
    coverProcessing: "Procesamiento de la imagen de portada",
    docxProcessing: "Procesamiento de documento Word (.docx)",
    docxInvalid: "El documento de Word leído no tiene páginas válidas.",
    tagGeneration: "Generación automática de géneros y etiquetas",
    dbCreation: "Creación de registro principal en la base de datos",
    dbPageSending: "Envío de páginas en la base de datos ({end} de {total})",
    publishSuccess: "¡Publicación completada con éxito!",
    stageFailed: "Fallo en la etapa: {stage}",
    realTimeError: "Error en Tiempo Real ({stage})",
    errorProcess: "Error durante el proceso: ",
    errorUpdatingStory: "Error al actualizar la historia: ",
    errorDeletingStory: "Error al eliminar la historia: ",
    errorUpdatingCommentStatus: "Error al actualizar el estado del comentario.",
    loginFailed: "El inicio de sesión falló",
    unknownAuthor: "Autor desconocido",
    recentDate: "Fecha reciente",
    approved: "Aprobado",
    pending: "Pendiente",
    rejected: "Rechazado",
    pages: "páginas",
    publishedAt: "Publicado el: {date}",
    confirmDeleteTitle: "Confirmar Eliminación",
    irreversibleAction: "Esta acción es irreversible",
    confirmDeletePrompt: "¿Está seguro de que desea eliminar la historia {title} permanentemente de la base de datos?",
    confirmDeleteWarning: "Esta acción eliminará la historia, todas sus páginas y todas las reseñas de la base de datos.",
    yesDelete: "Sí, Eliminar",
    noCommentsCategory: "Sin comentarios en esta categoría.",
    loadingComments: "Cargando comentarios para moderación...",
    editInSite: "Escribir",
    writeOnSite: "Escribir en el Sitio",
    uploadDocxFile: "Importar DOCX",
    saveDraft: "Guardar como Borrador",
    publishNow: "Publicar Historia",
    draft: "Borrador",
    drafts: "Borradores",
    published: "Publicados",
    isDraftBadge: "BORRADOR",
    isPublishedBadge: "PUBLICADO",
    editorTitle: "Editor de Historia",
    formatTitle: "Título Principal",
    formatSubtitle: "Subtítulo",
    formatParagraph: "Texto Normal",
    insertPageBreak: "Salto de Página",
    autoPageBreak: "Salto Automático de Página",
    wordsPerPage: "Palabras por página",
    pagesCount: "{count} página(s)",
    editInWriter: "Editar Texto en el Sitio",
    publishDraftConfirm: "¿Deseas publicar este borrador ahora?",
    draftSavedSuccess: "¡Borrador guardado con éxito!",
    draftPublishedSuccess: "¡Historia publicada con éxito!",
    filterStatus: "Filtrar por Estado",
    allStatus: "Todos los Estados",
    draftModeNotice: "Modo Borrador - Vista Previa de Autor",
    bold: "Negrita",
    italic: "Cursiva",
    underline: "Subrayado",
    strikethrough: "Tachado",
    alignLeft: "Izquierda",
    alignCenter: "Centrar",
    alignRight: "Derecha",
    alignJustify: "Justificar",
    bulletList: "Viñetas",
    numberList: "Numeración",
    quote: "Cita",
    typeContentHere: "Escribe tu historia aquí...",
    pagesGenerated: "Páginas generadas",

    // Advanced Typographic Accessibility & Themes
    openDyslexic: "OpenDyslexic (Accesibilidad)",
    fontFamily: "Fuente de Lectura",
    serifFont: "Serifada Elegante",
    sansFont: "Sin Serifas Moderna",
    dyslexicFont: "OpenDyslexic (Dislexia)",
    marginSize: "Márgenes",
    narrowMargin: "Estrecho",
    normalMargin: "Estándar",
    wideMargin: "Ancho",
    lineSpacing: "Interlineado",
    compactLine: "Compacto (1.4)",
    relaxedLine: "Agradable (1.8)",
    looseLine: "Expandido (2.2)",
    readingTheme: "Tema del Lector",
    sepiaTheme: "Sepia Acogedor",
    lightTheme: "Claro Estándar",
    darkTheme: "Oscuro Nocturno",

    // Analytics & Metrics
    analyticsDashboard: "Análisis y Métricas",
    avgReadingTime: "Tiempo Medio de Lectura",
    completionRate: "Tasa de Retención",
    totalViews: "Visualizaciones Totales",
    topPages: "Capítulos Más Leídos",
    retentionRate: "Conclusión de Lectura",
    readingMetrics: "Métricas de Lectores",
    readerEngagement: "Compromiso",
    authorMetrics: "Métricas de Rendimiento",

    // Scheduled Release
    scheduledRelease: "Lanzamiento Programado",
    scheduledReleaseAt: "Fecha/Hora de Lanzamiento",
    releaseScheduledFor: "Programado para {date}",
    scheduledStatus: "Programados",
    notYetReleased: "Historia aún no lanzada públicamente.",
    isScheduledBadge: "PROGRAMADO",

    // Multi-criteria Ratings
    plotRating: "Trama y Argumento",
    characterRating: "Desarrollo de Personajes",
    writingRating: "Calidad de Escritura",
    overallRating: "Calificación General",
    criteriaBreakdown: "Desglose por Criterios",

    // Playlists / Reading Lists
    playlists: "Playlists de Libros",
    createPlaylist: "Crear Lista de Lectura",
    playlistTitle: "Título de la Playlist",
    playlistDescription: "Descripción",
    addToPlaylist: "Añadir a la Lista",
    removeFromPlaylist: "Quitar de la Lista",
    publicPlaylists: "Colecciones Públicas",
    myPlaylists: "Mis Listas",
    emptyPlaylist: "Sin historias en esta lista.",
    isPublicList: "Lista Pública",
    managePlaylist: "Gestionar Lista",
    addStories: "Añadir Historias",
    editPlaylist: "Editar Lista",
    deletePlaylist: "Eliminar Lista",
    selectStoriesToAdd: "Selecciona historias para incluir en esta lista:",
    storiesCount: "{count} historias",

    // Achievements & Badges
    achievements: "Logros y Medallas",
    badges: "Medallas",
    myAchievements: "Mis Logros",
    unlockedAt: "Desbloqueado en",
    progress: "Progreso",

    // Offline Mode
    offlineMode: "Modo Offline",
    downloadForOffline: "Descargar para Leer Offline",
    downloadedOffline: "Guardado en el Dispositivo",
    removeOffline: "Eliminar Descarga",
    offlineAvailable: "Disponible Offline",
    savedOfflineStories: "Historias Descargadas",

    // Bookmarks & Private Notes
    bookmarks: "Marcadores",
    privateNotes: "Notas Privadas",
    addBookmark: "Marcar Página",
    addNote: "Añadir Nota",
    addNoteForPage: "Nueva nota en la Página {page}",
    yourNotes: "Mis Notas en esta Historia",
    notePlaceholder: "Escribe una reflexión o nota personal...",
    saveNote: "Guardar Nota",
    jumpToPage: "Ir a Pág. {page}",
    bookmarkSaved: "¡Página marcada con éxito!",
    backToAdmin: "Volver al Panel de Autor",
    pendingAutoSave: "Pendiente (30s)",
    autoSaveInterval: "Auto-guardado cada 30s",
    autoSaving: "Guardando...",
    savingDraft: "Guardando borrador...",
    draftSavedAt: "Borrador guardado a las {time}",
    autoSaveIn: "Auto-guardado en 30s",
    useMyName: "Usar mi Nombre: {name}",
    useMyUsername: "Usar mi @Usuario: @{username}",
    useUsernameOnly: "Usar mi Usuario: {username}",
    clearSchedule: "Limpiar Programación",
    previewPages: "Previsualizar Páginas",
    readerPreview: "Vista Previa de Lector",
    emptyPage: "Página vacía",
    pageBreak: "Salto de Página",
    pageBreakMarker: "--- Salto de Página (Pág. {page}) ---",
    pageBreakMarkerSimple: "--- Salto de Página ---",
    wordsCount: "{count} palabras",
    readTimeEstimate: "~{count} min lectura",
    deleteCommentText: "Borrar Texto",
    deleteAllComment: "Eliminar Todo",
    deleteCommentTextTitle: "Eliminar solo el texto",
    deleteCommentTextSubtitle: "La calificación de estrellas se preservará",
    deleteCommentTextConfirm: "¿Está seguro de que desea eliminar el texto del comentario de {name} en la obra {title}?",
    deleteCommentTextNotice: "El texto del comentario se eliminará permanentemente. La calificación de {rating} estrellas y el recuento general de calificaciones del libro no se verán afectados.",
    deleteAllCommentTitle: "Eliminar reseña completa",
    deleteAllCommentConfirm: "¿Está seguro de que desea eliminar toda la reseña (texto y calificación de {rating} estrellas) de {name} en la obra {title}?",
    deleteAllCommentNotice: "Esta acción eliminará completamente el comentario y las estrellas de la base de datos de manera definitiva.",
    activeReaders: "Lectores Activos",
    estimatedTimePerSession: "Tiempo estimado dedicado por sesión de lectura",
    readingStartedSingular: "lectura iniciada",
    readingStartedPlural: "lecturas iniciadas",
    completionRateNotice: "Tasa de finalización hasta la página final",
    performanceByStory: "Rendimiento por Historia",
    storyTableHead: "Historia",
    startsTableHead: "Inicios",
    avgProgressTableHead: "Progreso Medio",
    completionsTableHead: "Conclusiones",
    overallRatingTableHead: "Calificación General",
    pageSingular: "página",
    pagePlural: "páginas",
    retentionByPage: "Retención por Página",
    retentionDescription: "Porcentaje de lectores que alcanzaron o superaron cada página del libro.",
    readersSingular: "lector",
    readersPlural: "lectores",
    engagementAndReviews: "Compromiso y Reseñas",
    engagementDescription: "Estadísticas cualitativas extraídas de las reseñas públicas dejadas por los lectores.",
    avgOverallRating: "Nota Media General",
    totalReviews: "Total de Calificaciones",
    totalRegisteredUsers: "Total de Usuarios Registrados",
    totalFavoritesInSite: "Total de Favoritos en el Sitio",
    authorRequests: "Solicitudes de Autores",
    noRequestsPending: "Ninguna solicitud pendiente.",
    authorize: "Autorizar",
    noName: "Sin nombre",
    processingMetrics: "Procesando y compilando datos de lectura reales...",
    noReadingDataTitle: "Sin datos de lectura aún",
    noReadingDataDesc: "Las métricas de retención y progreso se generan automáticamente cuando los lectores comienzan a leer sus obras en la biblioteca.",
    styleTab: "Estilo",
    formatTab: "Formato",
    alignTab: "Alinear",
    extrasTab: "Extras",
    styleBold: "Negrita",
    styleItalic: "Itálica",
    styleUnderline: "Subrayado",
    styleStrike: "Tachado",
    styleLeft: "Izquierda",
    styleCenter: "Centro",
    styleRight: "Derecha",
    styleJustify: "Justificar",
    styleBullets: "Viñetas",
    styleNumbers: "Números",
    styleQuote: "Cita",
    stylePage: "Pág",
    updateWord: "Actualizar",
    accountType: "Tipo de Cuenta",
    readerRole: "Lector",
    authorRole: "Autor"
  },
  en: {
    // Navigation / Header / Footer
    library: "Collection",
    admin: "Author Area",
    toggleTheme: "Toggle light and dark mode",
    login: "Log In",
    register: "Register",
    logout: "Log Out",
    profile: "My Profile",
    version: "Version",
    online: "Online",
    bthDigital: "INK Digital",
    bthLibrary: "Collection",
    appBrand: "INKORA",
    language: "Language",
    
    // Home Page
    archive: "Collection",
    welcomeUser: "Welcome, {name}. Explore the digital collection.",
    exploreArchive: "Explore incredible stories and save your progress.",
    exploreStories: "Explore incredible stories and save your progress.",
    history: "History",
    favorites: "Favorites",
    searchPlaceholder: "Search title, author or genre...",
    mostRecent: "Most Recent",
    mostPopular: "Most Popular",
    noStoriesFound: "No stories found.",
    noFavoritesFound: "You haven't added any stories to favorites yet.",
    noHistoryFound: "Your reading history is empty.",
    continueReading: "Continue",
    by: "By",
    publishedOn: "Published on",
    pageOf: "Page {page} of {total}",
    readTime: "min read",
    
    // Reader Page
    backToLibrary: "Back to Library",
    readingResumed: "Reading Resumed",
    readingRestored: "Your reading was automatically restored on page {page}.",
    restartPage1: "Restart (Page 1)",
    goTo: "Go to:",
    loadingPage: "Loading page...",
    previous: "Previous",
    next: "Next",
    approvedComments: "Approved Comments",
    endOfStory: "End of Story",
    enjoyedReading: "Did you enjoy the reading? Leave your review.",
    reviewSent: "Review Submitted!",
    reviewSavedPending: "Your review has been registered. If you included a comment, it will be moderated before being published.",
    yourRating: "Your Rating",
    commentLabel: "Comment (Subject to moderation)",
    commentPlaceholder: "Write your opinion about the story...",
    moderationNotice: "Comments are reviewed by the administrator before becoming publicly visible.",
    sending: "Sending...",
    submitReview: "Submit Review",
    loadingStory: "Opening story...",
    storyNotFound: "Story not found.",
    reader: "Reader",
    errorSubmitReview: "Error submitting review.",
    pageNotFound: "Page not found.",
    errorLoadingPage: "Error loading page.",
    
    // Eye Comfort
    eyeComfort: "Eye Comfort",
    yellowFilter: "Yellow Filter",
    filterIntensity: "Filter Intensity",
    eyeComfortDescription: "Anti-fatigue yellow filter for smooth reading",
    off: "Off",
    
    // Auth Modal
    changePassword: "Change Password",
    myProfile: "My Profile",
    currentPassword: "Current Password",
    newPassword: "New Password",
    newPasswordPlaceholder: "Minimum 6 characters",
    currentPasswordPlaceholder: "Your current password",
    saveNewPassword: "Save New Password",
    updating: "Updating...",
    enterLibrary: "Enter the Library",
    createAccount: "Create an Account",
    recoverPassword: "Recover Password",
    accessFavorites: "Access your favorites and track your reading progress.",
    signupToSave: "Sign up to save your stories and reviews.",
    forgotPasswordInstructions: "Enter your email to set a new password.",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    confirmPasswordPlaceholder: "Enter password again",
    nameLabel: "Full Name",
    namePlaceholder: "Your name",
    usernameLabel: "Username (@)",
    usernamePlaceholder: "your_username",
    forgotPasswordLink: "Forgot my password",
    alreadyHaveAccount: "Already have an account?",
    dontHaveAccount: "Don't have an account yet?",
    forgotPasswordStep1Instructions: "Enter your account email to reset password directly on the platform.",
    passwordStrengthTip: "Tip: Use letters, numbers and at least 6 characters for a strong password.",
    passwordMismatch: "The passwords entered do not match.",
    passwordMinLength: "The password must be at least 6 characters.",
    fillAllFields: "Fill in the current password and the new password.",
    passwordChangedSuccess: "Your password has been changed successfully!",
    successLabel: "Success",
    errorLabel: "Error",
    forgotStep3Success: "Your password has been successfully reset on the site. You can now log in with your new credentials.",
    forgotStep3Title: "Password Reset!",
    forgotStep3Button: "Go to Login",
    entering: "Logging in...",
    creatingAccount: "Creating Account...",
    checking: "Verifying...",
    saving: "Saving...",
    passwordGuideline: "Your password must contain at least 6 characters.",
    passwordGuidelineStrength: "Create a secure password containing at least 6 characters, combining letters and numbers.",
    passwordGuidelineStrengthTitle: "Strong Password Guidelines",
    forgotStep1InstructionsEmail: "Enter your account email to reset your password directly on the platform.",
    
    // Admin Page
    adminPanel: "Author Panel",
    publish: "Publish",
    manage: "Manage",
    moderateComments: "Moderate Comments",
    superadmin: "Master Admin",
    writerNoticeFullScreen: "The editor will open in a new full-screen page for greater comfort.",
    useShortName: "Use: {name}",
    newCoverOptional: "(New)",
    storyTitle: "Story Title",
    storyTitlePlaceholder: "Ex: The Secret of the Stars",
    authorPlaceholder: "Ex: William Shakespeare",
    publishDate: "Publication Date",
    coverImageLabel: "Cover Image (JPEG/PNG)",
    coverImagePlaceholder: "Click to select cover",
    storyFileLabel: "Story File (DOCX)",
    storyFilePlaceholder: "Click to select DOCX",
    authorizeDrive: "Authorize Google Drive for Upload",
    publishStory: "Publish Story",
    publishing: "Publishing...",
    loadingStories: "Loading stories from the database...",
    noStoriesAdmin: "No stories found in the database.",
    editStory: "Edit Story",
    saveChanges: "Save Changes",
    cancel: "Cancel",
    deleteLabel: "Delete",
    editLabel: "Edit",
    commentsPending: "Pending",
    commentsApproved: "Approved",
    commentsRejected: "Rejected/Hidden",
    all: "All",
    updateList: "Update List",
    editTitle: "Title",
    editAuthor: "Author",
    editTags: "Tags (separated by comma)",
    editTagsPlaceholder: "Romance, Fantasy, Drama",
    refresh: "Refresh",
    loginWithGoogle: "Log in with Google",
    adminAccess: "Author Access",
    restrictedAccess: "Restricted Access",
    restrictedAccessDesc: "This area is exclusive for library authors.",
    goToLibrary: "Go to Library",
    exitAccount: "Log Out",
    emptyFieldsError: "The title and author cannot be empty.",
    storyUpdatedSuccess: "Story updated successfully!",
    storyDeletedSuccess: 'The story "{title}" was deleted from the database.',
    commentsApprovalTitle: "Comments Moderation",
    approve: "Approve",
    reject: "Reject",
    hide: "Hide",
    noCommentsFound: "No comments found.",
    statusLabel: "Status",
    userLabel: "User",
    textLabel: "Comment",
    ratingLabel: "Rating",
    actionsLabel: "Actions",
    any: "Any",
    startingFiles: "Starting files...",
    initialPrep: "Initial preparation",
    coverProcessing: "Cover image processing",
    docxProcessing: "Word document (.docx) processing",
    docxInvalid: "The read Word document does not have valid pages.",
    tagGeneration: "Automatic generation of genres and tags",
    dbCreation: "Creation of main record in the database",
    dbPageSending: "Sending pages in the database ({end} of {total})",
    publishSuccess: "Publishing completed successfully!",
    stageFailed: "Failed at stage: {stage}",
    realTimeError: "Real-Time Error ({stage})",
    errorProcess: "Error during process: ",
    errorUpdatingStory: "Error updating story: ",
    errorDeletingStory: "Error deleting story: ",
    errorUpdatingCommentStatus: "Error updating comment status.",
    loginFailed: "Login failed",
    unknownAuthor: "Unknown author",
    recentDate: "Recent date",
    approved: "Approved",
    pending: "Pending",
    rejected: "Rejected",
    pages: "pages",
    publishedAt: "Published on: {date}",
    confirmDeleteTitle: "Confirm Deletion",
    irreversibleAction: "This action is irreversible",
    confirmDeletePrompt: "Are you sure you want to delete the story {title} permanently from the database?",
    confirmDeleteWarning: "This action will remove the story, all its pages, and all reviews from the database.",
    yesDelete: "Yes, Delete",
    noCommentsCategory: "No comments in this category.",
    loadingComments: "Loading comments for moderation...",
    editInSite: "Write",
    writeOnSite: "Write on Site",
    uploadDocxFile: "Import DOCX",
    saveDraft: "Save as Draft",
    publishNow: "Publish Story",
    draft: "Draft",
    drafts: "Drafts",
    published: "Published",
    isDraftBadge: "DRAFT",
    isPublishedBadge: "PUBLISHED",
    editorTitle: "Story Editor",
    formatTitle: "Main Title",
    formatSubtitle: "Subtitle",
    formatParagraph: "Normal Text",
    insertPageBreak: "Page Break",
    autoPageBreak: "Auto Page Break",
    wordsPerPage: "Words per page",
    pagesCount: "{count} page(s)",
    editInWriter: "Edit Text on Site",
    publishDraftConfirm: "Do you want to publish this draft now?",
    draftSavedSuccess: "Draft saved successfully!",
    draftPublishedSuccess: "Story published successfully!",
    filterStatus: "Filter by Status",
    allStatus: "All Statuses",
    draftModeNotice: "Draft Mode - Author Preview",
    bold: "Bold",
    italic: "Italic",
    underline: "Underline",
    strikethrough: "Strikethrough",
    alignLeft: "Left",
    alignCenter: "Center",
    alignRight: "Right",
    alignJustify: "Justify",
    bulletList: "Bullet List",
    numberList: "Numbered List",
    quote: "Quote",
    typeContentHere: "Write your story here...",
    pagesGenerated: "Pages generated",

    // Advanced Typographic Accessibility & Themes
    openDyslexic: "OpenDyslexic (Accessibility)",
    fontFamily: "Reading Font",
    serifFont: "Elegant Serif",
    sansFont: "Modern Sans-Serif",
    dyslexicFont: "OpenDyslexic (Dyslexia)",
    marginSize: "Margins",
    narrowMargin: "Narrow",
    normalMargin: "Standard",
    wideMargin: "Wide",
    lineSpacing: "Line Spacing",
    compactLine: "Compact (1.4)",
    relaxedLine: "Relaxed (1.8)",
    looseLine: "Loose (2.2)",
    readingTheme: "Reader Theme",
    sepiaTheme: "Warm Sepia",
    lightTheme: "Standard Light",
    darkTheme: "Night Dark",

    // Analytics & Metrics
    analyticsDashboard: "Analytics & Metrics",
    avgReadingTime: "Avg. Reading Time",
    completionRate: "Retention Rate",
    totalViews: "Total Views",
    topPages: "Most Read Chapters",
    retentionRate: "Completion Rate",
    readingMetrics: "Reader Metrics",
    readerEngagement: "Engagement",
    authorMetrics: "Performance Metrics",

    // Scheduled Release
    scheduledRelease: "Scheduled Release",
    scheduledReleaseAt: "Release Date & Time",
    releaseScheduledFor: "Scheduled for {date}",
    scheduledStatus: "Scheduled",
    notYetReleased: "Story has not been publicly released yet.",
    isScheduledBadge: "SCHEDULED",

    // Multi-criteria Ratings
    plotRating: "Plot & Storyline",
    characterRating: "Character Development",
    writingRating: "Writing Quality",
    overallRating: "Overall Rating",
    criteriaBreakdown: "Detailed Criteria Breakdown",

    // Playlists / Reading Lists
    playlists: "Book Playlists",
    createPlaylist: "Create Reading List",
    playlistTitle: "Playlist Title",
    playlistDescription: "Description",
    addToPlaylist: "Add to Playlist",
    removeFromPlaylist: "Remove from Playlist",
    publicPlaylists: "Public Collections",
    myPlaylists: "My Lists",
    emptyPlaylist: "No stories in this playlist.",
    isPublicList: "Public List",
    managePlaylist: "Manage Playlist",
    addStories: "Add Stories",
    editPlaylist: "Edit Playlist",
    deletePlaylist: "Delete Playlist",
    selectStoriesToAdd: "Select stories to include in this playlist:",
    storiesCount: "{count} stories",

    // Achievements & Badges
    achievements: "Achievements & Badges",
    badges: "Badges",
    myAchievements: "My Achievements",
    unlockedAt: "Unlocked on",
    progress: "Progress",

    // Offline Mode
    offlineMode: "Offline Mode",
    downloadForOffline: "Download for Offline Reading",
    downloadedOffline: "Saved to Device",
    removeOffline: "Remove Download",
    offlineAvailable: "Available Offline",
    savedOfflineStories: "Downloaded Stories",

    // Bookmarks & Private Notes
    bookmarks: "Bookmarks",
    privateNotes: "Private Notes",
    addBookmark: "Bookmark Page",
    addNote: "Add Note",
    addNoteForPage: "New note on Page {page}",
    yourNotes: "My Notes on this Story",
    notePlaceholder: "Write a personal reflection or note...",
    saveNote: "Save Note",
    jumpToPage: "Jump to Page {page}",
    bookmarkSaved: "Page bookmarked successfully!",
    backToAdmin: "Back to Author Panel",
    pendingAutoSave: "Pending (30s)",
    autoSaveInterval: "Auto-save every 30s",
    autoSaving: "Saving...",
    savingDraft: "Saving draft...",
    draftSavedAt: "Draft saved at {time}",
    autoSaveIn: "Auto-save in 30s",
    useMyName: "Use my Name: {name}",
    useMyUsername: "Use my @Username: @{username}",
    useUsernameOnly: "Use my Username: {username}",
    clearSchedule: "Clear Schedule",
    previewPages: "Preview Pages",
    readerPreview: "Reader Preview",
    emptyPage: "Empty page",
    pageBreak: "Page Break",
    pageBreakMarker: "--- Page Break (Page {page}) ---",
    pageBreakMarkerSimple: "--- Page Break ---",
    wordsCount: "{count} words",
    readTimeEstimate: "~{count} min read",
    deleteCommentText: "Delete Text",
    deleteAllComment: "Delete All",
    deleteCommentTextTitle: "Delete text only",
    deleteCommentTextSubtitle: "The star rating will be preserved",
    deleteCommentTextConfirm: "Are you sure you want to delete the comment text from {name} on the work {title}?",
    deleteCommentTextNotice: "The comment text will be permanently deleted. The rating of {rating} stars and the overall book rating count will not change.",
    deleteAllCommentTitle: "Delete complete review",
    deleteAllCommentConfirm: "Are you sure you want to delete the entire review (text and {rating} star rating) from {name} on the work {title}?",
    deleteAllCommentNotice: "This action will completely and permanently remove the comment and stars from the database.",
    activeReaders: "Active Readers",
    estimatedTimePerSession: "Estimated time spent per reading session",
    readingStartedSingular: "reading started",
    readingStartedPlural: "readings started",
    completionRateNotice: "Completion rate to the final page",
    performanceByStory: "Performance by Story",
    storyTableHead: "Story",
    startsTableHead: "Starts",
    avgProgressTableHead: "Avg. Progress",
    completionsTableHead: "Completions",
    overallRatingTableHead: "Overall Rating",
    pageSingular: "page",
    pagePlural: "pages",
    retentionByPage: "Retention by Page",
    retentionDescription: "Percentage of readers who reached or exceeded each page of the book.",
    readersSingular: "reader",
    readersPlural: "readers",
    engagementAndReviews: "Engagement & Reviews",
    engagementDescription: "Qualitative statistics extracted from public reviews left by readers.",
    avgOverallRating: "Average Overall Rating",
    totalReviews: "Total Ratings",
    totalRegisteredUsers: "Total Registered Users",
    totalFavoritesInSite: "Total Favorites on the Site",
    authorRequests: "Author Requests",
    noRequestsPending: "No pending requests.",
    authorize: "Authorize",
    noName: "No name",
    processingMetrics: "Processing and compiling real reading data...",
    noReadingDataTitle: "No reading data yet",
    noReadingDataDesc: "Retention and progress metrics are automatically generated when readers start reading your works in the library.",
    styleTab: "Style",
    formatTab: "Format",
    alignTab: "Align",
    extrasTab: "Extras",
    styleBold: "Bold",
    styleItalic: "Italic",
    styleUnderline: "Underline",
    styleStrike: "Strikethrough",
    styleLeft: "Left",
    styleCenter: "Center",
    styleRight: "Right",
    styleJustify: "Justify",
    styleBullets: "Bullets",
    styleNumbers: "Numbers",
    styleQuote: "Quote",
    stylePage: "Page",
    updateWord: "Update",
    accountType: "Account Type",
    readerRole: "Reader",
    authorRole: "Author"
  },
  id: {
    // Navigation / Header / Footer
    library: "Koleksi",
    admin: "Area Penulis",
    toggleTheme: "Ubah mode terang dan gelap",
    login: "Masuk",
    register: "Daftar",
    logout: "Keluar Akun",
    profile: "Profil Saya",
    version: "Versi",
    online: "Online",
    bthDigital: "INK Digital",
    bthLibrary: "Koleksi",
    appBrand: "INKORA",
    language: "Bahasa",
    
    // Home Page
    archive: "Koleksi",
    welcomeUser: "Selamat datang, {name}. Jelajahi koleksi digital.",
    exploreArchive: "Jelajahi cerita luar biasa dan simpan progres membaca Anda.",
    exploreStories: "Jelajahi cerita luar biasa dan simpan progres membaca Anda.",
    history: "Riwayat",
    favorites: "Favorit",
    searchPlaceholder: "Cari judul, penulis, atau genre...",
    mostRecent: "Terbaru",
    mostPopular: "Terpopuler",
    noStoriesFound: "Cerita tidak ditemukan.",
    noFavoritesFound: "Anda belum menambahkan cerita ke favorit.",
    noHistoryFound: "Riwayat membaca Anda kosong.",
    continueReading: "Lanjutkan",
    by: "Oleh",
    publishedOn: "Diterbitkan pada",
    pageOf: "Hal. {page} dari {total}",
    readTime: "menit bacaan",
    
    // Reader Page
    backToLibrary: "Kembali ke Perpustakaan",
    readingResumed: "Melanjutkan Membaca",
    readingRestored: "Membaca Anda secara otomatis dipulihkan pada halaman {page}.",
    restartPage1: "Mulai Ulang (Hal. 1)",
    goTo: "Pergi ke:",
    loadingPage: "Memuat halaman...",
    previous: "Sebelumnya",
    next: "Berikutnya",
    approvedComments: "Komentar yang Disetujui",
    endOfStory: "Akhir Cerita",
    enjoyedReading: "Apakah Anda menikmati cerita ini? Tinggalkan ulasan Anda.",
    reviewSent: "Ulasan Terkirim!",
    reviewSavedPending: "Ulasan Anda telah terdaftar. Jika Anda menyertakan komentar, komentar tersebut akan dimoderasi sebelum diterbitkan.",
    yourRating: "Nilai Anda",
    commentLabel: "Komentar (Subjek moderasi)",
    commentPlaceholder: "Tulis pendapat Anda tentang cerita ini...",
    moderationNotice: "Komentar akan ditinjau oleh administrator sebelum ditampilkan secara publik.",
    sending: "Mengirim...",
    submitReview: "Kirim Ulasan",
    loadingStory: "Membuka cerita...",
    storyNotFound: "Cerita tidak ditemukan.",
    reader: "Pembaca",
    errorSubmitReview: "Gagal mengirim ulasan.",
    pageNotFound: "Halaman tidak ditemukan.",
    errorLoadingPage: "Gagal memuat halaman.",
    
    // Eye Comfort
    eyeComfort: "Kenyamanan Mata",
    yellowFilter: "Filter Kuning",
    filterIntensity: "Intensitas Filter",
    eyeComfortDescription: "Filter kuning anti-lelah untuk membaca dengan nyaman",
    off: "Mati",
    
    // Auth Modal
    changePassword: "Ubah Kata Sandi",
    myProfile: "Profil Saya",
    currentPassword: "Kata Sandi Sekarang",
    newPassword: "Kata Sandi Baru",
    newPasswordPlaceholder: "Minimal 6 karakter",
    currentPasswordPlaceholder: "Kata sandi sekarang Anda",
    saveNewPassword: "Simpan Kata Sandi Baru",
    updating: "Memperbarui...",
    enterLibrary: "Masuk Perpustakaan",
    createAccount: "Buat Akun",
    recoverPassword: "Pulihkan Kata Sandi",
    accessFavorites: "Akses favorit Anda dan lacak progres membaca Anda.",
    signupToSave: "Daftar untuk menyimpan cerita dan ulasan Anda.",
    forgotPasswordInstructions: "Masukkan email Anda untuk menyetel kata sandi baru.",
    email: "Email",
    password: "Kata Sandi",
    confirmPassword: "Konfirmasi Kata Sandi",
    confirmPasswordPlaceholder: "Masukkan kata sandi lagi",
    nameLabel: "Nama Lengkap",
    namePlaceholder: "Nama Anda",
    usernameLabel: "Nama Pengguna (@)",
    usernamePlaceholder: "nama_pengguna",
    forgotPasswordLink: "Lupa kata sandi",
    alreadyHaveAccount: "Sudah punya akun?",
    dontHaveAccount: "Belum punya akun?",
    forgotPasswordStep1Instructions: "Masukkan email akun Anda untuk menyetel ulang kata sandi langsung di platform.",
    passwordStrengthTip: "Tips: Gunakan huruf, angka, dan minimal 6 karakter untuk kata sandi yang kuat.",
    passwordMismatch: "Kata sandi yang dimasukkan tidak cocok.",
    passwordMinLength: "Kata sandi harus minimal 6 karakter.",
    fillAllFields: "Isi kata sandi saat ini dan kata sandi baru.",
    passwordChangedSuccess: "Kata sandi Anda berhasil diubah!",
    successLabel: "Sukses",
    errorLabel: "Kesalahan",
    forgotStep3Success: "Kata sandi Anda berhasil disetel ulang di situs. Anda sekarang dapat masuk dengan kredensial baru Anda.",
    forgotStep3Title: "Kata Sandi Disetel Ulang!",
    forgotStep3Button: "Pergi ke Masuk",
    entering: "Masuk...",
    creatingAccount: "Membuat Akun...",
    checking: "Memverifikasi...",
    saving: "Menyimpan...",
    passwordGuideline: "Kata sandi Anda harus berisi minimal 6 karakter.",
    passwordGuidelineStrength: "Buat kata sandi aman yang berisi minimal 6 karakter, menggabungkan huruf dan angka.",
    passwordGuidelineStrengthTitle: "Panduan Kata Sandi Kuat",
    forgotStep1InstructionsEmail: "Masukkan email akun Anda untuk menyetel ulang kata sandi Anda langsung di platform.",
    
    // Admin Page
    adminPanel: "Panel Penulis",
    publish: "Terbitkan",
    manage: "Kelola",
    moderateComments: "Moderat Komentar",
    superadmin: "Administrator Utama",
    writerNoticeFullScreen: "Editor akan dibuka di halaman layar penuh baru untuk kenyamanan lebih.",
    useShortName: "Gunakan: {name}",
    newCoverOptional: "(Baru)",
    storyTitle: "Judul Cerita",
    storyTitlePlaceholder: "Contoh: Rahasia Bintang",
    authorPlaceholder: "Contoh: Pramoedya Ananta Toer",
    publishDate: "Tanggal Terbit",
    coverImageLabel: "Gambar Sampul (JPEG/PNG)",
    coverImagePlaceholder: "Klik untuk memilih sampul",
    storyFileLabel: "File Cerita (DOCX)",
    storyFilePlaceholder: "Klik untuk memilih DOCX",
    authorizeDrive: "Otorisasi Google Drive untuk Unggah",
    publishStory: "Terbitkan Cerita",
    publishing: "Menerbitkan...",
    loadingStories: "Memuat cerita dari database...",
    noStoriesAdmin: "Cerita tidak ditemukan di database.",
    editStory: "Edit Cerita",
    saveChanges: "Simpan Perubahan",
    cancel: "Batal",
    deleteLabel: "Hapus",
    editLabel: "Edit",
    commentsPending: "Tertunda",
    commentsApproved: "Disetujui",
    commentsRejected: "Ditolak/Disembunyikan",
    all: "Semua",
    updateList: "Perbarui Daftar",
    editTitle: "Judul",
    editAuthor: "Penulis",
    editTags: "Tag (dipisahkan dengan koma)",
    editTagsPlaceholder: "Romansa, Fantasi, Drama",
    refresh: "Segarkan",
    loginWithGoogle: "Masuk dengan Google",
    adminAccess: "Akses Penulis",
    restrictedAccess: "Akses Terbatas",
    restrictedAccessDesc: "Area ini eksklusif untuk penulis perpustakaan.",
    goToLibrary: "Pergi ke Perpustakaan",
    exitAccount: "Keluar Akun",
    emptyFieldsError: "Judul dan penulis tidak boleh kosong.",
    storyUpdatedSuccess: "Cerita berhasil diperbarui!",
    storyDeletedSuccess: 'Cerita "{title}" telah dihapus dari database.',
    commentsApprovalTitle: "Moderasi Komentar",
    approve: "Setujui",
    reject: "Tolak",
    hide: "Sembunyikan",
    noCommentsFound: "Komentar tidak ditemukan.",
    statusLabel: "Status",
    userLabel: "Pengguna",
    textLabel: "Komentar",
    ratingLabel: "Penilaian",
    actionsLabel: "Tindakan",
    any: "Semua",
    startingFiles: "Memulai file...",
    initialPrep: "Persiapan awal",
    coverProcessing: "Pemrosesan gambar sampul",
    docxProcessing: "Pemrosesan dokumen Word (.docx)",
    docxInvalid: "Dokumen Word yang dibaca tidak memiliki halaman yang valid.",
    tagGeneration: "Pembuatan otomatis genre dan tag",
    dbCreation: "Pembuatan rekaman utama di database",
    dbPageSending: "Mengirim halaman di database ({end} dari {total})",
    publishSuccess: "Penerbitan berhasil diselesaikan!",
    stageFailed: "Gagal pada tahap: {stage}",
    realTimeError: "Kesalahan Real-Time ({stage})",
    errorProcess: "Kesalahan selama proses: ",
    errorUpdatingStory: "Gagal memperbarui cerita: ",
    errorDeletingStory: "Gagal menghapus cerita: ",
    errorUpdatingCommentStatus: "Gagal memperbarui status komentar.",
    loginFailed: "Login gagal",
    unknownAuthor: "Penulis tidak diketahui",
    recentDate: "Tanggal baru-baru ini",
    approved: "Disetujui",
    pending: "Tertunda",
    rejected: "Ditolak",
    pages: "halaman",
    publishedAt: "Diterbitkan pada: {date}",
    confirmDeleteTitle: "Konfirmasi Penghapusan",
    irreversibleAction: "Tindakan ini tidak dapat dibatalkan",
    confirmDeletePrompt: "Apakah Anda yakin ingin menghapus cerita {title} secara permanen dari database?",
    confirmDeleteWarning: "Tindakan ini akan menghapus cerita, semua halamannya, dan semua ulasan dari database.",
    yesDelete: "Ya, Hapus",
    noCommentsCategory: "Tidak ada komentar dalam kategori ini.",
    loadingComments: "Memuat komentar untuk moderasi...",
    editInSite: "Tulis",
    writeOnSite: "Tulis di Situs",
    uploadDocxFile: "Impor DOCX",
    saveDraft: "Simpan sebagai Draf",
    publishNow: "Terbitkan Cerita",
    draft: "Draf",
    drafts: "Draf",
    published: "Diterbitkan",
    isDraftBadge: "DRAF",
    isPublishedBadge: "DITERBITKAN",
    editorTitle: "Editor Cerita",
    formatTitle: "Judul Utama",
    formatSubtitle: "Subjudul",
    formatParagraph: "Teks Normal",
    insertPageBreak: "Pemisah Halaman",
    autoPageBreak: "Pemisah Halaman Otomatis",
    wordsPerPage: "Kata per halaman",
    pagesCount: "{count} halaman",
    editInWriter: "Edit Teks di Situs",
    publishDraftConfirm: "Apakah Anda ingin menerbitkan draf ini sekarang?",
    draftSavedSuccess: "Draf berhasil disimpan!",
    draftPublishedSuccess: "Cerita berhasil diterbitkan!",
    filterStatus: "Filter berdasarkan Status",
    allStatus: "Semua Status",
    draftModeNotice: "Mode Draf - Pratinjau Penulis",
    bold: "Tebal",
    italic: "Miring",
    underline: "Garis Bawah",
    strikethrough: "Coret",
    alignLeft: "Kiri",
    alignCenter: "Tengah",
    alignRight: "Kanan",
    alignJustify: "Rata Kanan Kiri",
    bulletList: "Daftar Simbol",
    numberList: "Daftar Angka",
    quote: "Kutipan",
    typeContentHere: "Tulis cerita Anda di sini...",
    pagesGenerated: "Halaman dihasilkan",

    // Advanced Typographic Accessibility & Themes
    openDyslexic: "OpenDyslexic (Aksesibilitas)",
    fontFamily: "Font Membaca",
    serifFont: "Serif Elegan",
    sansFont: "Sans-Serif Modern",
    dyslexicFont: "OpenDyslexic (Disleksia)",
    marginSize: "Margin",
    narrowMargin: "Sempit",
    normalMargin: "Standar",
    wideMargin: "Lebar",
    lineSpacing: "Jarak Antar Baris",
    compactLine: "Kompak (1.4)",
    relaxedLine: "Nyaman (1.8)",
    looseLine: "Longgar (2.2)",
    readingTheme: "Tema Pembaca",
    sepiaTheme: "Sepia Hangat",
    lightTheme: "Terang Standar",
    darkTheme: "Gelap Malam",

    // Analytics & Metrics
    analyticsDashboard: "Analisis & Metrik",
    avgReadingTime: "Rata-rata Waktu Membaca",
    completionRate: "Tingkat Retensi",
    totalViews: "Total Tampilan",
    topPages: "Bab Paling Banyak Dibaca",
    retentionRate: "Tingkat Penyelesaian",
    readingMetrics: "Metrik Pembaca",
    readerEngagement: "Keterlibatan",
    authorMetrics: "Metrik Kinerja",

    // Scheduled Release
    scheduledRelease: "Rilis Terjadwal",
    scheduledReleaseAt: "Tanggal & Waktu Rilis",
    releaseScheduledFor: "Dijadwalkan untuk {date}",
    scheduledStatus: "Dijadwalkan",
    notYetReleased: "Cerita belum dirilis secara publik.",
    isScheduledBadge: "DIJADWALKAN",

    // Multi-criteria Ratings
    plotRating: "Alur & Jalan Cerita",
    characterRating: "Pengembangan Karakter",
    writingRating: "Kualitas Penulisan",
    overallRating: "Penilaian Keseluruhan",
    criteriaBreakdown: "Rincian Berdasarkan Kriteria",

    // Playlists / Reading Lists
    playlists: "Daftar Putar Buku",
    createPlaylist: "Buat Daftar Bacaan",
    playlistTitle: "Judul Daftar Putar",
    playlistDescription: "Deskripsi",
    addToPlaylist: "Tambahkan ke Daftar",
    removeFromPlaylist: "Hapus dari Daftar",
    publicPlaylists: "Koleksi Publik",
    myPlaylists: "Daftar Saya",
    emptyPlaylist: "Tidak ada cerita dalam daftar ini.",
    isPublicList: "Daftar Publik",
    managePlaylist: "Kelola Playlist",
    addStories: "Tambah Cerita",
    editPlaylist: "Edit Playlist",
    deletePlaylist: "Hapus Playlist",
    selectStoriesToAdd: "Pilih cerita untuk dimasukkan ke playlist:",
    storiesCount: "{count} cerita",

    // Achievements & Badges
    achievements: "Pencapaian & Lencana",
    badges: "Lencana",
    myAchievements: "Pencapaian Saya",
    unlockedAt: "Dibuka pada",
    progress: "Kemajuan",

    // Offline Mode
    offlineMode: "Mode Luring",
    downloadForOffline: "Unduh untuk Membaca Luring",
    downloadedOffline: "Tersimpan di Perangkat",
    removeOffline: "Hapus Unduhan",
    offlineAvailable: "Tersedia Luring",
    savedOfflineStories: "Cerita Terunduh",

    // Bookmarks & Private Notes
    bookmarks: "Penanda Buku",
    privateNotes: "Catatan Pribadi",
    addBookmark: "Tandai Halaman",
    addNote: "Tambah Catatan",
    addNoteForPage: "Catatan baru di Halaman {page}",
    yourNotes: "Catatan Saya di Cerita Ini",
    notePlaceholder: "Tulis refleksi atau catatan pribadi...",
    saveNote: "Simpan Catatan",
    jumpToPage: "Lompat ke Hal. {page}",
    bookmarkSaved: "Halaman berhasil ditandai!",
    backToAdmin: "Kembali ke Panel Penulis",
    pendingAutoSave: "Tertunda (30d)",
    autoSaveInterval: "Penyimpanan otomatis setiap 30d",
    autoSaving: "Menyimpan...",
    savingDraft: "Menyimpan draf...",
    draftSavedAt: "Draf disimpan pada pukul {time}",
    autoSaveIn: "Simpan otomatis dalam 30d",
    useMyName: "Gunakan Nama Saya: {name}",
    useMyUsername: "Gunakan @Username Saya: @{username}",
    useUsernameOnly: "Gunakan Username Saya: {username}",
    clearSchedule: "Hapus Jadwal",
    previewPages: "Pratinjau Halaman",
    readerPreview: "Pratinjau Pembaca",
    emptyPage: "Halaman kosong",
    pageBreak: "Pemisah Halaman",
    pageBreakMarker: "--- Pemisah Halaman (Hal. {page}) ---",
    pageBreakMarkerSimple: "--- Pemisah Halaman ---",
    wordsCount: "{count} kata",
    readTimeEstimate: "~{count} mnt bacaan",
    deleteCommentText: "Hapus Teks",
    deleteAllComment: "Hapus Semua",
    deleteCommentTextTitle: "Hapus teks saja",
    deleteCommentTextSubtitle: "Peringkat bintang akan dipertahankan",
    deleteCommentTextConfirm: "Apakah Anda yakin ingin menghapus teks komentar dari {name} di karya {title}?",
    deleteCommentTextNotice: "Teks komentar akan dihapus secara permanen. Peringkat {rating} bintang dan jumlah peringkat buku secara keseluruhan tidak akan berubah.",
    deleteAllCommentTitle: "Hapus ulasan lengkap",
    deleteAllCommentConfirm: "Apakah Anda yakin ingin menghapus seluruh ulasan (teks dan peringkat {rating} bintang) dari {name} di karya {title}?",
    deleteAllCommentNotice: "Tindakan ini akan sepenuhnya dan permanen menghapus komentar dan bintang dari database.",
    activeReaders: "Pembaca Aktif",
    estimatedTimePerSession: "Perkiraan waktu yang dihabiskan per sesi membaca",
    readingStartedSingular: "membaca dimulai",
    readingStartedPlural: "membaca dimulai",
    completionRateNotice: "Tingkat penyelesaian hingga halaman akhir",
    performanceByStory: "Kinerja per Cerita",
    storyTableHead: "Cerita",
    startsTableHead: "Mulai",
    avgProgressTableHead: "Rata-rata Progres",
    completionsTableHead: "Selesai",
    overallRatingTableHead: "Peringkat Keseluruhan",
    pageSingular: "halaman",
    pagePlural: "halaman",
    retentionByPage: "Retensi per Halaman",
    retentionDescription: "Persentase pembaca yang mencapai atau melampaui setiap halaman buku.",
    readersSingular: "pembaca",
    readersPlural: "pembaca",
    engagementAndReviews: "Keterlibatan & Ulasan",
    engagementDescription: "Statistik kualitatif yang diekstrak dari ulasan publik yang ditinggalkan oleh pembaca.",
    avgOverallRating: "Rata-rata Peringkat",
    totalReviews: "Total Peringkat",
    totalRegisteredUsers: "Total Pengguna Terdaftar",
    totalFavoritesInSite: "Total Favorit di Situs",
    authorRequests: "Permintaan Penulis",
    noRequestsPending: "Tidak ada permintaan tertunda.",
    authorize: "Otorisasi",
    noName: "Tanpa nama",
    processingMetrics: "Memproses dan menyusun data membaca nyata...",
    noReadingDataTitle: "Belum ada data membaca",
    noReadingDataDesc: "Metrik retensi dan progres dibuat secara otomatis saat pembaca mulai membaca karya Anda di perpustakaan.",
    styleTab: "Gaya",
    formatTab: "Format",
    alignTab: "Rata",
    extrasTab: "Ekstra",
    styleBold: "Tebal",
    styleItalic: "Miring",
    styleUnderline: "Garis Bawah",
    styleStrike: "Coret",
    styleLeft: "Kiri",
    styleCenter: "Tengah",
    styleRight: "Kanan",
    styleJustify: "Rata",
    styleBullets: "Poin",
    styleNumbers: "Nomor",
    styleQuote: "Kutipan",
    stylePage: "Hal",
    updateWord: "Perbarui",
    accountType: "Tipe Akun",
    readerRole: "Pembaca",
    authorRole: "Penulis"
  }
} as const;

export type TranslationKey = keyof typeof translations.pt;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey, replace?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType>({} as LanguageContextType);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("site_language");
    if (saved === "pt" || saved === "es" || saved === "en" || saved === "id") {
      return saved as Language;
    }
    return "pt";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("site_language", lang);
  };

  const t = (key: TranslationKey, replace?: Record<string, string | number>): string => {
    const currentTranslations = translations[language] || translations.pt;
    let text = currentTranslations[key] || translations.pt[key] || String(key);
    
    if (replace) {
      Object.entries(replace).forEach(([k, v]) => {
        text = text.replace(`{${k}}`, String(v));
      });
    }
    
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
